/**
 * Algorithm traces for the ArrayViz scene.
 *
 * The trace is generated by actually running the algorithm, so what the bars do
 * and what the counters say can never disagree with each other. Add a new
 * algorithm by writing another builder that emits the same step shape.
 */

export type Tempo = {compare: number; swap: number; lock: number};

export const DEFAULT_TEMPO: Tempo = {compare: 14, swap: 26, lock: 8};

export type SortStep = {
  kind: 'compare' | 'swap' | 'lock';
  /** Array state at the start of the step. */
  arr: number[];
  /** Array state once the step resolves — differs only on a swap. */
  next: number[];
  /** Indices under active examination. */
  check: number[];
  /** Index of the running best (selection sort's minimum), if any. */
  keep: number | null;
  /** Slot being locked, for lock steps. */
  lockSlot: number | null;
  lockedLeft: number;
  lockedRight: number;
  start: number;
  duration: number;
  comparisons: number;
  swaps: number;
  pass: number;
  note: string;
};

export type Trace = {
  steps: SortStep[];
  total: number;
  sorted: number[];
  comparisons: number;
  swaps: number;
  passes: number;
};

const selection = (input: number[], t: Tempo): Trace => {
  const arr = [...input];
  const n = arr.length;
  const steps: SortStep[] = [];
  let f = 0;
  let comparisons = 0;
  let swaps = 0;

  for (let i = 0; i < n - 1; i++) {
    let minIdx = i;
    for (let j = i + 1; j < n; j++) {
      const better = arr[j] < arr[minIdx];
      comparisons++;
      steps.push({
        kind: 'compare',
        arr: [...arr],
        next: [...arr],
        check: [j],
        keep: minIdx,
        lockSlot: null,
        lockedLeft: i,
        lockedRight: 0,
        start: f,
        duration: t.compare,
        comparisons,
        swaps,
        pass: i + 1,
        note: better
          ? `${arr[j]} < ${arr[minIdx]}  —  new smallest`
          : `${arr[j]} > ${arr[minIdx]}  —  keep looking`,
      });
      f += t.compare;
      if (better) minIdx = j;
    }

    if (minIdx !== i) {
      const before = [...arr];
      [arr[i], arr[minIdx]] = [arr[minIdx], arr[i]];
      swaps++;
      steps.push({
        kind: 'swap',
        arr: before,
        next: [...arr],
        check: [i, minIdx],
        keep: minIdx,
        lockSlot: null,
        lockedLeft: i,
        lockedRight: 0,
        start: f,
        duration: t.swap,
        comparisons,
        swaps,
        pass: i + 1,
        note: `Swap ${before[minIdx]} into slot ${i}`,
      });
      f += t.swap;
    }

    steps.push({
      kind: 'lock',
      arr: [...arr],
      next: [...arr],
      check: [],
      keep: null,
      lockSlot: i,
      lockedLeft: i,
      lockedRight: 0,
      start: f,
      duration: t.lock,
      comparisons,
      swaps,
      pass: i + 1,
      note: `Slot ${i} is settled for good`,
    });
    f += t.lock;
  }

  return {steps, total: f, sorted: arr, comparisons, swaps, passes: n - 1};
};

const bubble = (input: number[], t: Tempo): Trace => {
  const arr = [...input];
  const n = arr.length;
  const steps: SortStep[] = [];
  let f = 0;
  let comparisons = 0;
  let swaps = 0;

  for (let i = 0; i < n - 1; i++) {
    for (let j = 0; j < n - 1 - i; j++) {
      const bigger = arr[j] > arr[j + 1];
      comparisons++;
      steps.push({
        kind: 'compare',
        arr: [...arr],
        next: [...arr],
        check: [j, j + 1],
        keep: null,
        lockSlot: null,
        lockedLeft: 0,
        lockedRight: i,
        start: f,
        duration: t.compare,
        comparisons,
        swaps,
        pass: i + 1,
        note: bigger
          ? `${arr[j]} > ${arr[j + 1]}  —  swap them`
          : `${arr[j]} < ${arr[j + 1]}  —  already in order`,
      });
      f += t.compare;

      if (bigger) {
        const before = [...arr];
        [arr[j], arr[j + 1]] = [arr[j + 1], arr[j]];
        swaps++;
        steps.push({
          kind: 'swap',
          arr: before,
          next: [...arr],
          check: [j, j + 1],
          keep: null,
          lockSlot: null,
          lockedLeft: 0,
          lockedRight: i,
          start: f,
          duration: t.swap,
          comparisons,
          swaps,
          pass: i + 1,
          note: `Bubble ${before[j]} to the right`,
        });
        f += t.swap;
      }
    }

    steps.push({
      kind: 'lock',
      arr: [...arr],
      next: [...arr],
      check: [],
      keep: null,
      lockSlot: n - 1 - i,
      lockedLeft: 0,
      lockedRight: i,
      start: f,
      duration: t.lock,
      comparisons,
      swaps,
      pass: i + 1,
      note: `Largest of the pass lands at slot ${n - 1 - i}`,
    });
    f += t.lock;
  }

  return {steps, total: f, sorted: arr, comparisons, swaps, passes: n - 1};
};

export const buildTrace = (
  algorithm: 'selection' | 'bubble',
  values: number[],
  tempo: Tempo = DEFAULT_TEMPO,
): Trace => (algorithm === 'bubble' ? bubble(values, tempo) : selection(values, tempo));

export const stepAt = (trace: Trace, frame: number): SortStep => {
  const {steps} = trace;
  for (let k = steps.length - 1; k >= 0; k--) {
    if (frame >= steps[k].start) return steps[k];
  }
  return steps[0];
};
