import type {FlashcardItem, VideoSpec} from '@video-kit/core/spec';

const animals: Record<string, FlashcardItem> = {
  lion: {label: 'Lion', emoji: '🦁', clue: 'has a big mane', color: '#F5A524'},
  elephant: {label: 'Elephant', emoji: '🐘', clue: 'has a long trunk', color: '#7D91AA'},
  giraffe: {label: 'Giraffe', emoji: '🦒', clue: 'has a long neck', color: '#F3B642'},
  monkey: {label: 'Monkey', emoji: '🐒', clue: 'loves to climb', color: '#A8754B'},
  dog: {label: 'Dog', emoji: '🐶', clue: 'says woof', color: '#7C5CFC'},
  cat: {label: 'Cat', emoji: '🐱', clue: 'says meow', color: '#FF6FAE'},
  cow: {label: 'Cow', emoji: '🐮', clue: 'says moo', color: '#4D596B'},
  horse: {label: 'Horse', emoji: '🐴', clue: 'runs fast', color: '#8B5A2B'},
  rabbit: {label: 'Rabbit', emoji: '🐰', clue: 'has long ears', color: '#EF7FAD'},
  penguin: {label: 'Penguin', emoji: '🐧', clue: 'waddles on ice', color: '#2F80ED'},
};

const allAnimals = [
  animals.lion,
  animals.elephant,
  animals.giraffe,
  animals.monkey,
  animals.dog,
  animals.cat,
  animals.cow,
  animals.horse,
  animals.rabbit,
  animals.penguin,
];

export const tenAnimals: VideoSpec = {
  channel: 'learn',
  slug: 'ten-animals',
  title: 'Learn 10 animals',
  template: 'early-learning-vocabulary',
  summary: 'Learn ten animal names with friendly pictures, simple clues, repetition, and a quick animal parade.',
  deliveries: ['youtube-short', 'instagram-reel'],
  audience: {ageBand: '3–7', level: 'beginner'},
  editorial: {
    language: 'en',
    objective: 'Help young learners recognize and say ten common animal names.',
    safetyStatus: 'approved',
  },
  scenes: [
    {
      type: 'title',
      durationInFrames: 90,
      kicker: 'Learn it fast',
      title: '10 Animals!',
      subtitle: 'Look, listen, and say each animal with me.',
      narration: 'Let us learn ten animals together!',
    },
    {
      type: 'flashcards',
      durationInFrames: 240,
      kicker: 'Animals 1 and 2',
      title: 'Lion and Elephant',
      items: [animals.lion, animals.elephant],
      prompt: 'Say it: lion … elephant!',
      narration: 'Lion. It has a big mane. Elephant. It has a long trunk. Say lion and elephant!',
    },
    {
      type: 'flashcards',
      durationInFrames: 240,
      kicker: 'Animals 3 and 4',
      title: 'Giraffe and Monkey',
      items: [animals.giraffe, animals.monkey],
      prompt: 'Say it: giraffe … monkey!',
      narration: 'Giraffe. It has a long neck. Monkey. It loves to climb. Say giraffe and monkey!',
    },
    {
      type: 'flashcards',
      durationInFrames: 240,
      kicker: 'Animals 5 and 6',
      title: 'Dog and Cat',
      items: [animals.dog, animals.cat],
      prompt: 'Say it: dog … cat!',
      narration: 'Dog. It says woof. Cat. It says meow. Say dog and cat!',
    },
    {
      type: 'flashcards',
      durationInFrames: 240,
      kicker: 'Animals 7 and 8',
      title: 'Cow and Horse',
      items: [animals.cow, animals.horse],
      prompt: 'Say it: cow … horse!',
      narration: 'Cow. It says moo. Horse. It runs fast. Say cow and horse!',
    },
    {
      type: 'flashcards',
      durationInFrames: 240,
      kicker: 'Animals 9 and 10',
      title: 'Rabbit and Penguin',
      items: [animals.rabbit, animals.penguin],
      prompt: 'Say it: rabbit … penguin!',
      narration: 'Rabbit. It has long ears. Penguin. It waddles on ice. Say rabbit and penguin!',
    },
    {
      type: 'flashcards',
      durationInFrames: 300,
      kicker: 'Animal parade',
      title: 'Can you name all ten?',
      items: allAnimals,
      prompt: 'Point to your favorite animal!',
      narration: 'Lion, elephant, giraffe, monkey, dog, cat, cow, horse, rabbit, and penguin. Which animal is your favorite?',
    },
    {
      type: 'outro',
      durationInFrames: 210,
      recap: ['10 animal names', '10 friendly clues', 'one wild parade'],
      tagline: 'Great job, animal explorer!',
      cta: 'Watch again and say them faster.',
      narration: 'Great job! Watch again and say all ten animals even faster.',
    },
  ],
};
