import type {VideoSpec} from '../types';

export const cdnToContainer: VideoSpec = {
  slug: 'cdn-to-container',
  title: 'What happens between the browser and your container',
  summary: 'The five hops a request takes on AWS, and where the latency actually goes.',
  handle: '@AIDataDynamics',
  formats: ['youtube', 'reel'],
  scenes: [
    {
      type: 'title',
      durationInFrames: 80,
      kicker: 'Cloud, visually',
      title: 'Browser to Container',
      subtitle: 'The five hops every request takes — and where the time goes.',
      narration: 'Every request takes five hops before your code runs. Here they are.',
    },
    {
      type: 'architecture',
      durationInFrames: 210,
      kicker: 'Request path',
      title: 'One GET, five hops',
      accent: 'teal',
      nodes: [
        {id: 'browser', label: 'Browser', sub: 'client', col: 0, row: 0, accent: 'violet'},
        {id: 'dns', label: 'Route 53', sub: 'dns', col: 1, row: 0},
        {id: 'cdn', label: 'CloudFront', sub: 'edge cache', col: 2, row: 0, accent: 'amber'},
        {id: 'alb', label: 'ALB', sub: 'load balancer', col: 1, row: 1},
        {id: 'ecs', label: 'ECS Fargate', sub: 'your container', col: 2, row: 1, accent: 'teal'},
        {id: 'rds', label: 'RDS', sub: 'postgres', col: 0, row: 1, accent: 'coral'},
      ],
      edges: [
        {from: 'browser', to: 'dns', label: 'resolve'},
        {from: 'dns', to: 'cdn'},
        {from: 'cdn', to: 'alb', label: 'miss'},
        {from: 'alb', to: 'ecs'},
        {from: 'ecs', to: 'rds', label: 'query', dashed: true},
      ],
      reveal: [['browser'], ['dns'], ['cdn'], ['alb'], ['ecs', 'rds']],
      trace: {path: ['browser', 'dns', 'cdn', 'alb', 'ecs'], label: 'following one cache miss'},
      narration: 'DNS, edge cache, load balancer, container, database. A cache hit stops at hop three.',
    },
    {
      type: 'stats',
      durationInFrames: 140,
      kicker: 'Latency budget',
      title: 'Where the milliseconds go',
      cards: [
        {label: 'edge hit', value: '~15 ms', note: 'never reaches your origin', accent: 'amber'},
        {label: 'origin hop', value: '~90 ms', note: 'ALB plus container cold path', accent: 'teal'},
        {label: 'db query', value: '~40 ms', note: 'the part you actually control', accent: 'coral'},
      ],
      narration: 'An edge hit is six times cheaper than reaching your origin at all.',
    },
    {
      type: 'code',
      durationInFrames: 200,
      title: 'Cache what you can',
      lang: 'terraform',
      filename: 'cloudfront.tf',
      accent: 'teal',
      lines: [
        'default_cache_behavior {',
        '  target_origin_id       = "alb-origin"',
        '  viewer_protocol_policy = "redirect-to-https"',
        '',
        '  cache_policy_id = aws_cloudfront_cache_policy.spa.id',
        '  compress        = true',
        '}',
      ],
      focus: [
        {lines: [5], note: 'The cache policy is the whole game — it decides what never reaches your container.'},
        {lines: [6], note: 'Compression at the edge, not in your app. Free CPU back.'},
      ],
      narration: 'The cache policy decides which requests never reach your container at all.',
    },
    {
      type: 'callout',
      durationInFrames: 100,
      accent: 'amber',
      text: 'The fastest request is the one your origin never sees.',
      attribution: 'the entire point of a CDN',
      narration: 'The fastest request is the one your origin never sees.',
    },
    {
      type: 'outro',
      durationInFrames: 90,
      recap: ['browser → dns → edge', '  edge hit  → done', '  edge miss → alb → container → db'],
      handle: '@AIDataDynamics',
      tagline: 'Cloud concepts, drawn out.',
      cta: 'Follow for more',
      narration: 'Five hops. Cache the first three away.',
    },
  ],
};
