import type {ColorSwatch, VideoSpec} from '../../types';

const colors: Record<string, ColorSwatch> = {
  red: {name: 'Red', hex: '#EF3340', example: 'an apple', emoji: '🍎'},
  blue: {name: 'Blue', hex: '#2F80ED', example: 'a butterfly', emoji: '🦋'},
  yellow: {name: 'Yellow', hex: '#FFD43B', example: 'the sun', emoji: '☀️'},
  green: {name: 'Green', hex: '#27AE60', example: 'a leaf', emoji: '🍃'},
  orange: {name: 'Orange', hex: '#FF8A1F', example: 'an orange', emoji: '🍊'},
  purple: {name: 'Purple', hex: '#8E5AD7', example: 'grapes', emoji: '🍇'},
  pink: {name: 'Pink', hex: '#FF6FAE', example: 'a flower', emoji: '🌸'},
  brown: {name: 'Brown', hex: '#8B5A2B', example: 'a bear', emoji: '🐻'},
  black: {name: 'Black', hex: '#17191F', example: 'a black cat', emoji: '🐈‍⬛'},
  white: {name: 'White', hex: '#FFFFFF', example: 'a snowflake', emoji: '❄️'},
};

const allColors = [
  colors.red,
  colors.blue,
  colors.yellow,
  colors.green,
  colors.orange,
  colors.purple,
  colors.pink,
  colors.brown,
  colors.black,
  colors.white,
];

export const tenColors: VideoSpec = {
  channel: 'learn',
  slug: 'ten-colors',
  title: 'Learn 10 colors',
  template: 'early-learning-vocabulary',
  summary: 'Learn ten common colors with bright swatches, familiar objects, repetition, and a quick review.',
  deliveries: ['youtube-short', 'instagram-reel'],
  audience: {ageBand: '3–7', level: 'beginner'},
  editorial: {
    language: 'en',
    objective: 'Help young learners recognize and say ten common color names.',
    safetyStatus: 'approved',
  },
  scenes: [
    {
      type: 'title',
      durationInFrames: 90,
      kicker: 'Learn it fast',
      title: '10 Colors!',
      subtitle: 'Look, listen, and say each color with me.',
      narration: 'Let us learn ten colors together!',
    },
    {
      type: 'colors',
      durationInFrames: 240,
      kicker: 'Colors 1 and 2',
      title: 'Red and Blue',
      items: [colors.red, colors.blue],
      prompt: 'Say it: red … blue!',
      narration: 'Red, like an apple. Blue, like a butterfly. Say red and blue!',
    },
    {
      type: 'colors',
      durationInFrames: 240,
      kicker: 'Colors 3 and 4',
      title: 'Yellow and Green',
      items: [colors.yellow, colors.green],
      prompt: 'Say it: yellow … green!',
      narration: 'Yellow, like the sun. Green, like a leaf. Say yellow and green!',
    },
    {
      type: 'colors',
      durationInFrames: 240,
      kicker: 'Colors 5 and 6',
      title: 'Orange and Purple',
      items: [colors.orange, colors.purple],
      prompt: 'Say it: orange … purple!',
      narration: 'Orange, like an orange. Purple, like grapes. Say orange and purple!',
    },
    {
      type: 'colors',
      durationInFrames: 240,
      kicker: 'Colors 7 and 8',
      title: 'Pink and Brown',
      items: [colors.pink, colors.brown],
      prompt: 'Say it: pink … brown!',
      narration: 'Pink, like a flower. Brown, like a bear. Say pink and brown!',
    },
    {
      type: 'colors',
      durationInFrames: 240,
      kicker: 'Colors 9 and 10',
      title: 'Black and White',
      items: [colors.black, colors.white],
      prompt: 'Say it: black … white!',
      narration: 'Black, like a black cat. White, like a snowflake. Say black and white!',
    },
    {
      type: 'colors',
      durationInFrames: 300,
      kicker: 'Color parade',
      title: 'Can you name all ten?',
      items: allColors,
      prompt: 'Point to your favorite color!',
      narration: 'Red, blue, yellow, green, orange, purple, pink, brown, black, and white. Which color is your favorite?',
    },
    {
      type: 'outro',
      durationInFrames: 210,
      recap: ['10 colors', '10 bright examples', 'one colorful world'],
      tagline: 'Great job, color explorer!',
      cta: 'Watch again and say them faster.',
      narration: 'Great job! Watch again and say all ten colors even faster.',
    },
  ],
};
