import type {FlashcardItem, VideoSpec} from '../../types';

const countries: Record<string, FlashcardItem> = {
  india: {rank: 1, label: 'India', emoji: '🇮🇳', clue: 'Capital: New Delhi', color: '#FF8A1F'},
  china: {rank: 2, label: 'China', emoji: '🇨🇳', clue: 'Capital: Beijing', color: '#EF3340'},
  unitedStates: {
    rank: 3,
    label: 'United States',
    emoji: '🇺🇸',
    clue: 'Capital: Washington, D.C.',
    color: '#2F80ED',
  },
  indonesia: {
    rank: 4,
    label: 'Indonesia',
    emoji: '🇮🇩',
    clue: 'New capital: Nusantara',
    color: '#E84B55',
  },
  pakistan: {rank: 5, label: 'Pakistan', emoji: '🇵🇰', clue: 'Capital: Islamabad', color: '#16845B'},
  nigeria: {rank: 6, label: 'Nigeria', emoji: '🇳🇬', clue: 'Capital: Abuja', color: '#18A979'},
  brazil: {rank: 7, label: 'Brazil', emoji: '🇧🇷', clue: 'Capital: Brasília', color: '#2F9E44'},
  bangladesh: {rank: 8, label: 'Bangladesh', emoji: '🇧🇩', clue: 'Capital: Dhaka', color: '#188A63'},
  russia: {rank: 9, label: 'Russia', emoji: '🇷🇺', clue: 'Capital: Moscow', color: '#4D7FCB'},
  ethiopia: {rank: 10, label: 'Ethiopia', emoji: '🇪🇹', clue: 'Capital: Addis Ababa', color: '#F5A524'},
  mexico: {rank: 11, label: 'Mexico', emoji: '🇲🇽', clue: 'Capital: Mexico City', color: '#219653'},
  japan: {rank: 12, label: 'Japan', emoji: '🇯🇵', clue: 'Capital: Tokyo', color: '#E84B55'},
  egypt: {rank: 13, label: 'Egypt', emoji: '🇪🇬', clue: 'Capital: Cairo', color: '#D99B2B'},
  philippines: {rank: 14, label: 'Philippines', emoji: '🇵🇭', clue: 'Capital: Manila', color: '#2F80ED'},
  drCongo: {rank: 15, label: 'DR Congo', emoji: '🇨🇩', clue: 'Capital: Kinshasa', color: '#3A8DDE'},
  vietnam: {rank: 16, label: 'Vietnam', emoji: '🇻🇳', clue: 'Capital: Hanoi', color: '#EF3340'},
  iran: {rank: 17, label: 'Iran', emoji: '🇮🇷', clue: 'Capital: Tehran', color: '#18A979'},
  turkey: {rank: 18, label: 'Türkiye', emoji: '🇹🇷', clue: 'Capital: Ankara', color: '#D93B49'},
  germany: {rank: 19, label: 'Germany', emoji: '🇩🇪', clue: 'Capital: Berlin', color: '#4D596B'},
  thailand: {rank: 20, label: 'Thailand', emoji: '🇹🇭', clue: 'Capital: Bangkok', color: '#7C5CFC'},
};

const firstTen = [
  countries.india,
  countries.china,
  countries.unitedStates,
  countries.indonesia,
  countries.pakistan,
  countries.nigeria,
  countries.brazil,
  countries.bangladesh,
  countries.russia,
  countries.ethiopia,
];

const secondTen = [
  countries.mexico,
  countries.japan,
  countries.egypt,
  countries.philippines,
  countries.drCongo,
  countries.vietnam,
  countries.iran,
  countries.turkey,
  countries.germany,
  countries.thailand,
];

export const twentyCountriesCapitals: VideoSpec = {
  channel: 'learn',
  slug: 'twenty-countries-capitals',
  title: '20 countries and their capitals',
  template: 'geography-vocabulary',
  summary: 'Learn the twenty most populous countries and their capital cities with flags, ranking badges, and two quick review rounds.',
  deliveries: ['youtube-short', 'instagram-reel'],
  audience: {ageBand: '7–12', level: 'beginner'},
  editorial: {
    language: 'en',
    objective: 'Help students recognize the twenty most populous countries and recall their capital cities.',
    safetyStatus: 'approved',
    sources: [
      {
        title: 'United Nations World Population Prospects 2024',
        url: 'https://population.un.org/wpp/',
      },
      {
        title: 'UNGEGN World Geographical Names Database',
        url: 'https://unstats.un.org/unsd/geoinfo/geonames/',
      },
      {
        title: 'Indonesia Law Number 3 of 2022 on the National Capital',
        url: 'https://jdih.kemenkeu.go.id/dok/uu-3-tahun-2022/view',
      },
    ],
  },
  scenes: [
    {
      type: 'title',
      durationInFrames: 90,
      kicker: 'Geography in 90 seconds',
      title: '20 Countries & Capitals',
      subtitle: 'The world’s most populous countries, from 1 to 20.',
      narration: 'Learn twenty countries and their capitals with me!',
    },
    {
      type: 'flashcards',
      durationInFrames: 180,
      kicker: 'Ranks 1 and 2',
      title: 'India and China',
      items: [countries.india, countries.china],
      prompt: 'India → New Delhi · China → Beijing',
      narration: 'India — New Delhi. China — Beijing. Say both country-capital pairs!',
    },
    {
      type: 'flashcards',
      durationInFrames: 180,
      kicker: 'Ranks 3 and 4',
      title: 'United States and Indonesia',
      items: [countries.unitedStates, countries.indonesia],
      prompt: 'United States → Washington, D.C. · Indonesia → Nusantara',
      narration: 'United States — Washington, D.C. Indonesia — Nusantara. Say both pairs!',
    },
    {
      type: 'flashcards',
      durationInFrames: 180,
      kicker: 'Ranks 5 and 6',
      title: 'Pakistan and Nigeria',
      items: [countries.pakistan, countries.nigeria],
      prompt: 'Pakistan → Islamabad · Nigeria → Abuja',
      narration: 'Pakistan — Islamabad. Nigeria — Abuja. Say both country-capital pairs!',
    },
    {
      type: 'flashcards',
      durationInFrames: 180,
      kicker: 'Ranks 7 and 8',
      title: 'Brazil and Bangladesh',
      items: [countries.brazil, countries.bangladesh],
      prompt: 'Brazil → Brasília · Bangladesh → Dhaka',
      narration: 'Brazil — Brasília. Bangladesh — Dhaka. Say both country-capital pairs!',
    },
    {
      type: 'flashcards',
      durationInFrames: 180,
      kicker: 'Ranks 9 and 10',
      title: 'Russia and Ethiopia',
      items: [countries.russia, countries.ethiopia],
      prompt: 'Russia → Moscow · Ethiopia → Addis Ababa',
      narration: 'Russia — Moscow. Ethiopia — Addis Ababa. Say both country-capital pairs!',
    },
    {
      type: 'flashcards',
      durationInFrames: 180,
      kicker: 'Ranks 11 and 12',
      title: 'Mexico and Japan',
      items: [countries.mexico, countries.japan],
      prompt: 'Mexico → Mexico City · Japan → Tokyo',
      narration: 'Mexico — Mexico City. Japan — Tokyo. Say both country-capital pairs!',
    },
    {
      type: 'flashcards',
      durationInFrames: 180,
      kicker: 'Ranks 13 and 14',
      title: 'Egypt and Philippines',
      items: [countries.egypt, countries.philippines],
      prompt: 'Egypt → Cairo · Philippines → Manila',
      narration: 'Egypt — Cairo. Philippines — Manila. Say both country-capital pairs!',
    },
    {
      type: 'flashcards',
      durationInFrames: 180,
      kicker: 'Ranks 15 and 16',
      title: 'DR Congo and Vietnam',
      items: [countries.drCongo, countries.vietnam],
      prompt: 'DR Congo → Kinshasa · Vietnam → Hanoi',
      narration: 'DR Congo — Kinshasa. Vietnam — Hanoi. Say both country-capital pairs!',
    },
    {
      type: 'flashcards',
      durationInFrames: 180,
      kicker: 'Ranks 17 and 18',
      title: 'Iran and Türkiye',
      items: [countries.iran, countries.turkey],
      prompt: 'Iran → Tehran · Türkiye → Ankara',
      narration: 'Iran — Tehran. Türkiye — Ankara. Say both country-capital pairs!',
    },
    {
      type: 'flashcards',
      durationInFrames: 180,
      kicker: 'Ranks 19 and 20',
      title: 'Germany and Thailand',
      items: [countries.germany, countries.thailand],
      prompt: 'Germany → Berlin · Thailand → Bangkok',
      narration: 'Germany — Berlin. Thailand — Bangkok. Say both country-capital pairs!',
    },
    {
      type: 'flashcards',
      durationInFrames: 300,
      kicker: 'Review 1 to 10',
      title: 'Can you recall each capital?',
      items: firstTen,
      showCluesInCompact: true,
      prompt: 'Pause and read the first ten pairs.',
      narration: 'Here are the first ten. Pause and name each capital as you point to its country.',
    },
    {
      type: 'flashcards',
      durationInFrames: 300,
      kicker: 'Review 11 to 20',
      title: 'Ten more to remember',
      items: secondTen,
      showCluesInCompact: true,
      prompt: 'Pause and read the next ten pairs.',
      narration: 'Now review eleven through twenty. Point to each flag and say its capital.',
    },
    {
      type: 'outro',
      durationInFrames: 210,
      recap: ['20 countries', '20 capital cities', 'one world to explore'],
      tagline: 'Great job, geography explorer!',
      cta: 'Watch again and test your memory.',
      narration: 'Great job! Watch again, cover the capital names, and test your memory.',
    },
  ],
};
