import type {VideoSpec} from '../../types';

export const embeddingsMotionExplainer: VideoSpec = {
  channel: 'tech',
  slug: 'embeddings-motion-explainer',
  title: 'How Embeddings Find Meaning',
  template: 'motion-explainer-whiteboard',
  summary:
    'A progressive whiteboard explanation of how semantic search matches meaning instead of exact wording.',
  fps: 30,
  deliveries: ['youtube-short', 'instagram-reel'],
  audience: {level: 'beginner'},
  editorial: {
    language: 'en-US',
    objective:
      'Explain that semantic search compares vector representations of queries and document chunks.',
  },
  voice: {speed: 1, maxSpeed: 1},
  audio: 'audio/tech/embeddings-motion-explainer/master.wav',
  captionTimings: 'audio/tech/embeddings-motion-explainer/words.json',
  captions: true,
  scenes: [
    {
      id: 'meaning-map',
      type: 'motionCanvas',
      style: 'whiteboard-light',
      motion: {intensity: 'dynamic', ambient: true},
      durationInFrames: 990,
      chapterTitle: 'Meaning, not spelling',
      narration:
        "You search for money back, but the best page only says refund. It still appears because semantic search usually converts your query and each document chunk into vectors: lists of numbers that capture patterns in meaning. An embedding model learns this useful geometry from patterns in large collections of training text. The query and the refund page land close together, while an unrelated banana page lands far away. Search compares those positions and returns the nearest useful chunks. That is embeddings in practice: matching meaning instead of exact wording. What search result has felt like it read your mind?",
      headline: 'Meaning, not spelling',
      hookEndFrame: 90,
      elements: [
        {
          id: 'hook',
          kind: 'text',
          text: '“money back” finds “refund” — how?',
          role: 'headline',
          x: 50,
          y: 6,
          width: 94,
        },
        {
          id: 'search',
          kind: 'search',
          query: 'money back',
          x: 50,
          y: 17,
          width: 78,
          typewriter: true,
        },
        {
          id: 'vector-label',
          kind: 'text',
          text: 'text → vector → position',
          role: 'label',
          x: 50,
          y: 29,
          width: 72,
        },
        {
          id: 'meaning-cluster',
          kind: 'cluster',
          label: 'similar meaning',
          x: 51,
          y: 54,
          width: 58,
          height: 31,
        },
        {
          id: 'refund',
          kind: 'dot',
          label: 'refund page',
          tone: 'positive',
          x: 41,
          y: 51,
          size: 1.2,
        },
        {
          id: 'money-back',
          kind: 'dot',
          label: 'money back query',
          tone: 'accent',
          x: 60,
          y: 49,
          size: 1.25,
        },
        {
          id: 'banana',
          kind: 'dot',
          label: 'banana page',
          tone: 'negative',
          x: 83,
          y: 69,
          size: 1,
        },
        {
          id: 'similarity',
          kind: 'connector',
          from: 'money-back',
          to: 'refund',
          label: 'nearby',
          arrow: true,
        },
        {
          id: 'unrelated',
          kind: 'connector',
          from: 'refund',
          to: 'banana',
          label: 'far away',
          dashed: true,
          arrow: true,
        },
        {
          id: 'orbit-curious',
          kind: 'mascot',
          expression: 'curious',
          label: 'Orbit',
          x: 13,
          y: 72,
        },
        {
          id: 'payoff',
          kind: 'text',
          text: 'Embeddings match meaning, not exact wording.',
          role: 'payoff',
          x: 50,
          y: 79,
          width: 88,
        },
        {
          id: 'cta',
          kind: 'text',
          text: 'What search result felt like it read your mind? ↓',
          role: 'cta',
          x: 50,
          y: 88,
          width: 92,
        },
      ],
      actions: [
        {target: 'hook', type: 'reveal', atFrame: 0, durationFrames: 15, anchor: {phrase: 'You search', offsetFrames: -6}},
        {target: 'search', type: 'reveal', atFrame: 18, durationFrames: 18, anchor: {phrase: 'money back', offsetFrames: -3}},
        {target: 'search', type: 'highlight', atFrame: 60, durationFrames: 24, anchor: {phrase: 'refund'}},
        {target: 'vector-label', type: 'reveal', atFrame: 100, durationFrames: 18, anchor: {phrase: 'semantic search', offsetFrames: -4}},
        {target: 'meaning-cluster', type: 'draw', atFrame: 210, durationFrames: 30, anchor: {phrase: 'vectors', offsetFrames: -5}},
        {target: 'refund', type: 'reveal', atFrame: 235, durationFrames: 18, anchor: {phrase: 'refund page', offsetFrames: -4}},
        {target: 'money-back', type: 'reveal', atFrame: 310, durationFrames: 18, anchor: {phrase: 'query and the refund', offsetFrames: -5}},
        {target: 'similarity', type: 'draw', atFrame: 350, durationFrames: 26, anchor: {phrase: 'close together', offsetFrames: -6}},
        {target: 'similarity', type: 'travel', atFrame: 370, durationFrames: 46, anchor: {phrase: 'close together'}},
        {target: 'similarity', type: 'highlight', atFrame: 390, durationFrames: 26, anchor: {phrase: 'close together'}},
        {target: 'refund', type: 'pulse', atFrame: 405, durationFrames: 40, anchor: {phrase: 'close together', offsetFrames: 6}},
        {target: 'banana', type: 'reveal', atFrame: 430, durationFrames: 18, anchor: {phrase: 'banana page', offsetFrames: -4}},
        {target: 'unrelated', type: 'draw', atFrame: 470, durationFrames: 34, anchor: {phrase: 'far away', offsetFrames: -4}},
        {target: 'orbit-curious', type: 'reveal', atFrame: 515, durationFrames: 20, anchor: {phrase: 'Search compares', offsetFrames: -5}},
        {target: 'money-back', type: 'highlight', atFrame: 600, durationFrames: 26, anchor: {phrase: 'nearest useful chunks', offsetFrames: -3}},
        {target: 'refund', type: 'highlight', atFrame: 630, durationFrames: 26, anchor: {phrase: 'nearest useful chunks', offsetFrames: 5}},
        {target: 'payoff', type: 'reveal', atFrame: 760, durationFrames: 24, anchor: {phrase: 'embeddings in practice', offsetFrames: -5}},
        {target: 'payoff', type: 'highlight', atFrame: 800, durationFrames: 24, anchor: {phrase: 'matching meaning'}},
        {target: 'cta', type: 'reveal', atFrame: 900, durationFrames: 20, anchor: {phrase: 'What search result', offsetFrames: -5}},
      ],
    },
  ],
};
