import type {VideoSpec} from '../../types';

export const pythonListsVsGenerators: VideoSpec = {
  channel: 'tech',
  slug: 'python-lists-vs-generators',
  title: 'Python Lists vs Generators in 60 Seconds',
  template: 'motion-explainer-cinematic',
  summary:
    'See what Python creates, stores, pauses, and resumes when you choose a list or generator expression.',
  fps: 30,
  deliveries: ['youtube-short', 'instagram-reel'],
  audience: {level: 'beginner'},
  voice: {speed: 1, maxSpeed: 1},
  audio: 'audio/tech/python-lists-vs-generators/master.wav',
  captionTimings: 'audio/tech/python-lists-vs-generators/words.json',
  captions: true,
  soundtrack: {
    music: {
      src: 'audio/music/momentum-grid.m4a',
      credit: 'Video Kit — Momentum Grid',
      license: 'Original project-generated instrumental',
      volume: 0.2,
      loop: true,
      fadeInFrames: 18,
      fadeOutFrames: 60,
    },
    ducking: {
      gain: 0.48,
      attackFrames: 10,
      releaseFrames: 20,
    },
  },
  editorial: {
    language: 'en-US',
    objective:
      'Explain the runtime and practical trade-offs between list comprehensions and generator expressions.',
    sources: [
      {
        title: 'Python Functional Programming HOWTO — Generator expressions and list comprehensions',
        url: 'https://docs.python.org/3/howto/functional.html#generator-expressions-and-list-comprehensions',
      },
      {
        title: 'Python Language Reference — Yield expressions',
        url: 'https://docs.python.org/3/reference/expressions.html#yield-expressions',
      },
      {
        title: 'Python Glossary — generator iterator',
        url: 'https://docs.python.org/3/glossary.html#term-generator-iterator',
      },
    ],
  },
  scenes: [
    {
      id: 'lists-vs-generators',
      type: 'motionCanvas',
      style: 'midnight-code',
      motion: {intensity: 'dynamic', ambient: true},
      effects: {
        camera: 'push-in',
        particles: 'data-stream',
        glow: 'strong',
        scanlines: true,
        vignette: true,
      },
      durationInFrames: 1_800,
      hookEndFrame: 90,
      chapterTitle: 'Materialize everything or stream one value',
      narration:
        'These two Python lines look alike, but they run very differently. Square brackets build a list. Python loops now, calculates every square, and stores every result in memory. Parentheses build a generator expression. Python returns a generator object before calculating the results. When next, or a for loop, asks for a value, Python resumes the generator, calculates one item, yields it, then pauses with its state saved. Ask again, and it continues. Lists support indexing, length, reuse, and repeated passes. Generators produce values once as you iterate, so an exhausted generator stays exhausted. Use a list when you need the whole collection or random access. Use a generator for large files, database rows, model batches, or streaming pipelines where holding everything wastes memory. Same loop idea; different runtime. Follow for more Python foundations for AI engineering, save this comparison, and use it in your next project.',
      headline: 'Python lists vs generators',
      elements: [
        {
          id: 'hook',
          kind: 'text',
          text: 'Same loop. Very different runtime.',
          role: 'headline',
          x: 50,
          y: 5,
          width: 94,
        },
        {
          id: 'list-code',
          kind: 'code',
          code: 'squares = [n * n for n in data]',
          label: 'list comprehension · eager',
          x: 50,
          y: 16,
          width: 92,
          typewriter: true,
        },
        {
          id: 'generator-code',
          kind: 'code',
          code: 'squares = (n * n for n in data)',
          label: 'generator expression · lazy',
          x: 50,
          y: 27,
          width: 92,
          typewriter: true,
        },
        {
          id: 'runtime-code',
          kind: 'code',
          code: 'squares = (n * n for n in data)\nfirst = next(squares)\nprint(first)',
          label: 'generator runtime · line by line',
          x: 50,
          y: 22,
          width: 92,
          lineNumbers: true,
        },
        {
          id: 'list-label',
          kind: 'text',
          text: 'LIST · COMPUTE NOW',
          role: 'label',
          x: 26,
          y: 38,
          width: 44,
        },
        {
          id: 'list-space',
          kind: 'cluster',
          label: 'all results retained',
          x: 26,
          y: 54,
          width: 44,
          height: 27,
        },
        {id: 'list-0', kind: 'shape', shape: 'rounded-square', label: '0', tone: 'neutral', x: 10, y: 52, width: 7, height: 9, animation: 'breathe'},
        {id: 'list-1', kind: 'shape', shape: 'square', label: '1', tone: 'neutral', x: 18, y: 49, width: 7, height: 9},
        {id: 'list-4', kind: 'shape', shape: 'diamond', label: '4', tone: 'accent', x: 26, y: 54, width: 8, height: 10, animation: 'wobble'},
        {id: 'list-9', kind: 'shape', shape: 'hexagon', label: '9', tone: 'neutral', x: 34, y: 49, width: 7, height: 9},
        {id: 'list-16', kind: 'shape', shape: 'rounded-square', label: '16', tone: 'neutral', x: 42, y: 52, width: 7, height: 9},
        {
          id: 'generator-label',
          kind: 'text',
          text: 'GENERATOR · COMPUTE ON DEMAND',
          role: 'label',
          x: 75,
          y: 38,
          width: 48,
        },
        {
          id: 'generator-space',
          kind: 'cluster',
          label: 'execution state retained',
          x: 74,
          y: 54,
          width: 39,
          height: 27,
        },
        {
          id: 'next-call',
          kind: 'shape',
          shape: 'diamond',
          label: 'next()',
          tone: 'accent',
          x: 62,
          y: 53,
          width: 12,
          height: 15,
          animation: 'wobble',
        },
        {
          id: 'yielded-value',
          kind: 'shape',
          shape: 'hexagon',
          label: 'one value',
          tone: 'positive',
          x: 86,
          y: 53,
          width: 14,
          height: 17,
          animation: 'breathe',
        },
        {
          id: 'resume-flow',
          kind: 'connector',
          from: 'next-call',
          to: 'yielded-value',
          arrow: true,
        },
        {
          id: 'resume-label',
          kind: 'text',
          text: 'RESUME → YIELD → PAUSE',
          role: 'label',
          x: 74,
          y: 46,
          width: 38,
        },
        {
          id: 'streaming-use',
          kind: 'text',
          text: 'FILES · DATABASE ROWS · MODEL BATCHES · STREAMS',
          role: 'payoff',
          x: 50,
          y: 70,
          width: 94,
        },
        {
          id: 'list-choice',
          kind: 'text',
          text: 'LIST  →  index, reuse, repeat',
          role: 'payoff',
          x: 27,
          y: 80,
          width: 46,
        },
        {
          id: 'generator-choice',
          kind: 'text',
          text: 'GENERATOR  →  stream once',
          role: 'payoff',
          x: 74,
          y: 80,
          width: 45,
        },
        {
          id: 'final-kicker',
          kind: 'text',
          text: 'CHOOSE BY HOW VALUES FLOW',
          role: 'label',
          x: 50,
          y: 39,
          width: 78,
        },
        {
          id: 'recap',
          kind: 'text',
          text: 'WHOLE COLLECTION  ↔  ONE-VALUE FLOW',
          role: 'cta',
          x: 50,
          y: 54,
          width: 94,
        },
      ],
      actions: [
        {target: 'hook', type: 'reveal', atFrame: 0, durationFrames: 16, anchor: {phrase: 'These two Python lines', offsetFrames: -3}},
        {target: 'hook', type: 'highlight', atFrame: 45, durationFrames: 24, anchor: {phrase: 'very differently'}},
        {target: 'list-code', type: 'reveal', atFrame: 110, durationFrames: 22, anchor: {phrase: 'Square brackets build a list', offsetFrames: -4}},
        {target: 'list-label', type: 'reveal', atFrame: 190, durationFrames: 16, anchor: {phrase: 'Python loops now', offsetFrames: -4}},
        {target: 'list-space', type: 'draw', atFrame: 225, durationFrames: 28, anchor: {phrase: 'calculates every square', offsetFrames: -4}},
        {target: 'list-0', type: 'reveal', atFrame: 250, durationFrames: 14, anchor: {phrase: 'calculates every square', offsetFrames: -6}},
        {target: 'list-1', type: 'reveal', atFrame: 275, durationFrames: 14, anchor: {phrase: 'calculates every square', offsetFrames: 0}},
        {target: 'list-4', type: 'reveal', atFrame: 300, durationFrames: 14, anchor: {phrase: 'calculates every square', offsetFrames: 6}},
        {target: 'list-9', type: 'reveal', atFrame: 325, durationFrames: 14, anchor: {phrase: 'stores every result', offsetFrames: -3}},
        {target: 'list-16', type: 'reveal', atFrame: 350, durationFrames: 14, anchor: {phrase: 'stores every result', offsetFrames: 4}},
        {target: 'list-space', type: 'highlight', atFrame: 380, durationFrames: 26, anchor: {phrase: 'stores every result'}},
        {target: 'generator-code', type: 'reveal', atFrame: 420, durationFrames: 22, anchor: {phrase: 'Parentheses build a generator expression', offsetFrames: -5}},
        {target: 'generator-label', type: 'reveal', atFrame: 505, durationFrames: 16, anchor: {phrase: 'returns a generator object', offsetFrames: -5}},
        {target: 'generator-space', type: 'draw', atFrame: 545, durationFrames: 28, anchor: {phrase: 'before calculating the results', offsetFrames: -5}},
        {target: 'list-code', type: 'hide', atFrame: 600, durationFrames: 16, anchor: {phrase: 'When next', offsetFrames: -8}},
        {target: 'generator-code', type: 'hide', atFrame: 600, durationFrames: 16, anchor: {phrase: 'When next', offsetFrames: -8}},
        {target: 'runtime-code', type: 'reveal', atFrame: 605, durationFrames: 18, anchor: {phrase: 'When next', offsetFrames: -6}},
        {target: 'runtime-code', type: 'focus-line', line: 1, note: 'Creates the generator object; values remain deferred.', atFrame: 610, durationFrames: 32, anchor: {phrase: 'When next', offsetFrames: -3}},
        {target: 'next-call', type: 'reveal', atFrame: 610, durationFrames: 18, anchor: {phrase: 'When next', offsetFrames: -4}},
        {target: 'next-call', type: 'pulse', atFrame: 650, durationFrames: 40, anchor: {phrase: 'asks for a value'}},
        {target: 'next-call', type: 'spin', atFrame: 652, durationFrames: 34, anchor: {phrase: 'asks for a value', offsetFrames: 2}},
        {target: 'resume-flow', type: 'draw', atFrame: 700, durationFrames: 30, anchor: {phrase: 'resumes the generator', offsetFrames: -4}},
        {target: 'resume-label', type: 'reveal', atFrame: 700, durationFrames: 18, anchor: {phrase: 'resumes the generator', offsetFrames: -4}},
        {target: 'runtime-code', type: 'execute-line', line: 2, note: 'next() resumes execution for one item.', output: 'first = 0 · paused', atFrame: 704, durationFrames: 50, anchor: {phrase: 'resumes the generator'}},
        {target: 'resume-flow', type: 'travel', atFrame: 735, durationFrames: 52, anchor: {phrase: 'calculates one item', offsetFrames: -3}},
        {target: 'yielded-value', type: 'reveal', atFrame: 755, durationFrames: 18, anchor: {phrase: 'yields it', offsetFrames: -3}},
        {target: 'yielded-value', type: 'bounce', atFrame: 758, durationFrames: 28, anchor: {phrase: 'yields it'}},
        {target: 'runtime-code', type: 'execute-line', line: 3, note: 'The caller receives the yielded value.', output: '0', atFrame: 760, durationFrames: 42, anchor: {phrase: 'yields it', offsetFrames: 1}},
        {target: 'generator-space', type: 'highlight', atFrame: 820, durationFrames: 26, anchor: {phrase: 'state saved'}},
        {target: 'resume-flow', type: 'highlight', atFrame: 895, durationFrames: 24, anchor: {phrase: 'Ask again'}},
        {target: 'runtime-code', type: 'hide', atFrame: 980, durationFrames: 18, anchor: {phrase: 'Lists support indexing', offsetFrames: -10}},
        {target: 'list-choice', type: 'reveal', atFrame: 1_000, durationFrames: 20, anchor: {phrase: 'Lists support indexing', offsetFrames: -4}},
        {target: 'list-choice', type: 'highlight', atFrame: 1_075, durationFrames: 24, anchor: {phrase: 'repeated passes'}},
        {target: 'generator-choice', type: 'reveal', atFrame: 1_130, durationFrames: 20, anchor: {phrase: 'Generators produce values once', offsetFrames: -4}},
        {target: 'generator-choice', type: 'highlight', atFrame: 1_385, durationFrames: 24, anchor: {phrase: 'stays exhausted'}},
        {target: 'list-choice', type: 'pulse', atFrame: 1_300, durationFrames: 42, anchor: {phrase: 'whole collection'}},
        {target: 'streaming-use', type: 'reveal', atFrame: 1_390, durationFrames: 22, anchor: {phrase: 'Use a generator for large files', offsetFrames: -4}},
        {target: 'streaming-use', type: 'highlight', atFrame: 1_480, durationFrames: 24, anchor: {phrase: 'model batches'}},
        {target: 'generator-choice', type: 'pulse', atFrame: 1_550, durationFrames: 42, anchor: {phrase: 'holding everything wastes memory'}},
        {target: 'hook', type: 'hide', atFrame: 1_000, durationFrames: 18, anchor: {phrase: 'Lists support indexing', offsetFrames: -8}},
        {target: 'list-code', type: 'hide', atFrame: 1_300, durationFrames: 18, anchor: {phrase: 'Use a list', offsetFrames: -8}},
        {target: 'generator-code', type: 'hide', atFrame: 1_300, durationFrames: 18, anchor: {phrase: 'Use a list', offsetFrames: -8}},
        {target: 'streaming-use', type: 'hide', atFrame: 1_640, durationFrames: 18, anchor: {phrase: 'Same loop idea', offsetFrames: -8}},
        {target: 'list-label', type: 'hide', atFrame: 1_640, durationFrames: 18, anchor: {phrase: 'Same loop idea', offsetFrames: -8}},
        {target: 'list-space', type: 'hide', atFrame: 1_640, durationFrames: 18, anchor: {phrase: 'Same loop idea', offsetFrames: -8}},
        {target: 'list-0', type: 'hide', atFrame: 1_640, durationFrames: 18, anchor: {phrase: 'Same loop idea', offsetFrames: -8}},
        {target: 'list-1', type: 'hide', atFrame: 1_640, durationFrames: 18, anchor: {phrase: 'Same loop idea', offsetFrames: -8}},
        {target: 'list-4', type: 'hide', atFrame: 1_640, durationFrames: 18, anchor: {phrase: 'Same loop idea', offsetFrames: -8}},
        {target: 'list-9', type: 'hide', atFrame: 1_640, durationFrames: 18, anchor: {phrase: 'Same loop idea', offsetFrames: -8}},
        {target: 'list-16', type: 'hide', atFrame: 1_640, durationFrames: 18, anchor: {phrase: 'Same loop idea', offsetFrames: -8}},
        {target: 'generator-label', type: 'hide', atFrame: 1_640, durationFrames: 18, anchor: {phrase: 'Same loop idea', offsetFrames: -8}},
        {target: 'generator-space', type: 'hide', atFrame: 1_640, durationFrames: 18, anchor: {phrase: 'Same loop idea', offsetFrames: -8}},
        {target: 'next-call', type: 'hide', atFrame: 1_640, durationFrames: 18, anchor: {phrase: 'Same loop idea', offsetFrames: -8}},
        {target: 'yielded-value', type: 'hide', atFrame: 1_640, durationFrames: 18, anchor: {phrase: 'Same loop idea', offsetFrames: -8}},
        {target: 'resume-flow', type: 'hide', atFrame: 1_640, durationFrames: 18, anchor: {phrase: 'Same loop idea', offsetFrames: -8}},
        {target: 'resume-label', type: 'hide', atFrame: 1_640, durationFrames: 18, anchor: {phrase: 'Same loop idea', offsetFrames: -8}},
        {target: 'final-kicker', type: 'reveal', atFrame: 1_642, durationFrames: 20, anchor: {phrase: 'Same loop idea', offsetFrames: -7}},
        {target: 'recap', type: 'reveal', atFrame: 1_650, durationFrames: 24, anchor: {phrase: 'Same loop idea', offsetFrames: -4}},
        {target: 'final-kicker', type: 'highlight', atFrame: 1_685, durationFrames: 22, anchor: {phrase: 'different runtime', offsetFrames: -3}},
        {target: 'recap', type: 'highlight', atFrame: 1_700, durationFrames: 26, anchor: {phrase: 'different runtime'}},
      ],
    },
  ],
};
