import type {VideoSpec} from '../../types';

export const ragIn60Seconds: VideoSpec = {
  channel: 'tech',
  slug: 'rag-in-60-seconds',
  title: 'How RAG Works in 60 Seconds',
  template: 'motion-explainer-whiteboard',
  summary:
    'A progressive visual explanation of indexing, retrieval, prompt augmentation, grounded generation, and RAG limitations.',
  fps: 30,
  deliveries: ['youtube-short', 'instagram-reel'],
  audience: {level: 'beginner'},
  editorial: {
    language: 'en-US',
    objective:
      'Explain the complete retrieval-augmented generation flow without implying retraining or guaranteed factuality.',
  },
  voice: {speed: 1, maxSpeed: 1},
  audio: 'audio/tech/rag-in-60-seconds/master.wav',
  captionTimings: 'audio/tech/rag-in-60-seconds/words.json',
  captions: true,
  scenes: [
    {
      id: 'rag-flow',
      type: 'motionCanvas',
      style: 'whiteboard-light',
      motion: {intensity: 'dynamic', ambient: true},
      durationInFrames: 1_800,
      chapterTitle: 'Retrieve, augment, generate',
      narration:
        'An LLM cannot answer from private documents it never saw. RAG lets it retrieve evidence before answering. First, before anyone asks, documents are split into useful chunks. An embedding model converts each chunk into a vector, and a vector database stores the vector with its original text. A user asks, “What is our refund policy?” The same embedding model creates a query vector. Retrieval compares it with stored vectors and selects the most relevant chunks. The system does not train the language model again. It builds a prompt with instructions, the question, and retrieved evidence. The LLM reads that context and generates an answer grounded in those chunks, ideally with citations. If evidence is missing, it should say so. RAG can reduce unsupported answers, but does not guarantee truth. Poor chunks, weak retrieval, or stale documents can still fail. Remember the flow: index documents, retrieve evidence, augment the prompt, then generate.',
      headline: 'How does an LLM use your documents?',
      hookEndFrame: 90,
      elements: [
        {
          id: 'hook',
          kind: 'text',
          text: 'How does an LLM use knowledge it never learned?',
          role: 'headline',
          x: 50,
          y: 5,
          width: 94,
        },
        {
          id: 'question',
          kind: 'search',
          query: 'What is our refund policy?',
          x: 50,
          y: 15,
          width: 88,
          typewriter: true,
        },
        {
          id: 'index-label',
          kind: 'text',
          text: '1  INDEX DOCUMENTS',
          role: 'label',
          x: 27,
          y: 26,
          width: 44,
        },
        {
          id: 'document-space',
          kind: 'cluster',
          label: 'vector database',
          x: 29,
          y: 44,
          width: 45,
          height: 27,
        },
        {
          id: 'policy',
          kind: 'shape',
          shape: 'document',
          label: 'R',
          tone: 'positive',
          x: 22,
          y: 40,
          width: 12,
          height: 15,
          animation: 'breathe',
        },
        {
          id: 'handbook',
          kind: 'shape',
          shape: 'document',
          label: 'H',
          tone: 'neutral',
          x: 38,
          y: 45,
          width: 10,
          height: 13,
        },
        {
          id: 'faq',
          kind: 'shape',
          shape: 'document',
          label: 'FAQ',
          tone: 'accent',
          x: 23,
          y: 51,
          width: 9,
          height: 12,
        },
        {
          id: 'query-vector',
          kind: 'shape',
          shape: 'ring',
          label: 'Q',
          tone: 'accent',
          x: 76,
          y: 39,
          width: 14,
          height: 17,
          animation: 'wobble',
        },
        {
          id: 'retrieve',
          kind: 'connector',
          from: 'query-vector',
          to: 'policy',
          label: '2  RETRIEVE',
          arrow: true,
        },
        {
          id: 'prompt',
          kind: 'text',
          text: '3  PROMPT = instructions + question + evidence',
          role: 'payoff',
          x: 50,
          y: 64,
          width: 92,
        },
        {
          id: 'orbit-llm',
          kind: 'mascot',
          expression: 'thinking',
          label: 'LLM',
          x: 18,
          y: 76,
        },
        {
          id: 'answer',
          kind: 'text',
          text: '4  GROUNDED ANSWER + CITATIONS',
          role: 'payoff',
          x: 63,
          y: 75,
          width: 64,
        },
        {
          id: 'caution',
          kind: 'text',
          text: 'Better evidence ≠ guaranteed truth',
          role: 'label',
          x: 54,
          y: 82,
          width: 86,
        },
        {
          id: 'recap',
          kind: 'text',
          text: 'INDEX → RETRIEVE → AUGMENT → GENERATE',
          role: 'cta',
          x: 50,
          y: 88,
          width: 94,
        },
      ],
      actions: [
        {target: 'hook', type: 'reveal', atFrame: 0, durationFrames: 16, anchor: {phrase: 'An LLM cannot', offsetFrames: -5}},
        {target: 'hook', type: 'highlight', atFrame: 45, durationFrames: 22, anchor: {phrase: 'private documents it never saw'}},
        {target: 'question', type: 'reveal', atFrame: 95, durationFrames: 18, anchor: {phrase: 'RAG lets it', offsetFrames: -4}},
        {target: 'index-label', type: 'reveal', atFrame: 160, durationFrames: 16, anchor: {phrase: 'before anyone asks', offsetFrames: -5}},
        {target: 'document-space', type: 'draw', atFrame: 220, durationFrames: 30, anchor: {phrase: 'documents are split', offsetFrames: -5}},
        {target: 'policy', type: 'reveal', atFrame: 270, durationFrames: 16, anchor: {phrase: 'useful chunks', offsetFrames: -3}},
        {target: 'handbook', type: 'reveal', atFrame: 310, durationFrames: 16, anchor: {phrase: 'embedding model', offsetFrames: -3}},
        {target: 'faq', type: 'reveal', atFrame: 350, durationFrames: 16, anchor: {phrase: 'vector database', offsetFrames: -3}},
        {target: 'question', type: 'highlight', atFrame: 470, durationFrames: 24, anchor: {phrase: 'What is our refund policy', offsetFrames: -4}},
        {target: 'query-vector', type: 'reveal', atFrame: 560, durationFrames: 18, anchor: {phrase: 'query vector', offsetFrames: -4}},
        {target: 'query-vector', type: 'pulse', atFrame: 585, durationFrames: 42, anchor: {phrase: 'query vector'}},
        {target: 'retrieve', type: 'draw', atFrame: 650, durationFrames: 34, anchor: {phrase: 'selects the most relevant chunks', offsetFrames: -6}},
        {target: 'retrieve', type: 'travel', atFrame: 670, durationFrames: 54, anchor: {phrase: 'selects the most relevant chunks'}},
        {target: 'policy', type: 'highlight', atFrame: 700, durationFrames: 24, anchor: {phrase: 'most relevant chunks'}},
        {target: 'policy', type: 'pulse', atFrame: 715, durationFrames: 42, anchor: {phrase: 'most relevant chunks', offsetFrames: 5}},
        {target: 'prompt', type: 'reveal', atFrame: 880, durationFrames: 22, anchor: {phrase: 'builds a prompt', offsetFrames: -5}},
        {target: 'prompt', type: 'highlight', atFrame: 960, durationFrames: 22, anchor: {phrase: 'retrieved evidence'}},
        {target: 'orbit-llm', type: 'reveal', atFrame: 1_040, durationFrames: 20, anchor: {phrase: 'The LLM reads', offsetFrames: -5}},
        {target: 'answer', type: 'reveal', atFrame: 1_100, durationFrames: 22, anchor: {phrase: 'generates an answer', offsetFrames: -5}},
        {target: 'answer', type: 'highlight', atFrame: 1_190, durationFrames: 24, anchor: {phrase: 'with citations', offsetFrames: -3}},
        {target: 'caution', type: 'reveal', atFrame: 1_310, durationFrames: 22, anchor: {phrase: 'does not guarantee truth', offsetFrames: -5}},
        {target: 'caution', type: 'highlight', atFrame: 1_390, durationFrames: 24, anchor: {phrase: 'Poor chunks', offsetFrames: -3}},
        {target: 'recap', type: 'reveal', atFrame: 1_590, durationFrames: 24, anchor: {phrase: 'remember the flow', offsetFrames: -5}},
        {target: 'recap', type: 'highlight', atFrame: 1_660, durationFrames: 24, anchor: {phrase: 'index documents'}},
      ],
    },
  ],
};
