import type {
  CategoryDefinition,
  TemplateDefinition,
  ThemeDefinition,
} from './contracts';

const fonts = {
  display: "'Hanken Grotesk', system-ui, sans-serif",
  body: "'Hanken Grotesk', system-ui, sans-serif",
  mono: "'JetBrains Mono', ui-monospace, monospace",
};

export const DEFAULT_THEMES: ThemeDefinition[] = [
  {
    id: 'tech',
    color: {
      bg: '#0a0e0c',
      bgDeep: '#060907',
      surface: '#141f1a',
      surfaceHi: '#1b2a24',
      line: '#26362f',
      lineHi: '#33473f',
      text: '#e9e7e2',
      textDim: '#b6beb9',
      muted: '#7e8c86',
    },
    accents: {
      primary: '#f5a524',
      secondary: '#a78bfa',
      success: '#2dd4bf',
      attention: '#ff6b5b',
      info: '#60a5fa',
    },
    font: {...fonts, display: "'Fraunces', Georgia, serif"},
    frameBackground:
      'radial-gradient(120% 80% at 50% 0%, rgba(20,31,26,0.34), transparent 60%)',
    chrome: {progressHeight: 5, progressOpacity: 0.85, captionRadius: 14},
  },
  {
    id: 'learn',
    color: {
      bg: '#fff8ea',
      bgDeep: '#fff0cf',
      surface: '#ffffff',
      surfaceHi: '#fff2d6',
      line: '#f1d49a',
      lineHi: '#d99b2b',
      text: '#24324a',
      textDim: '#52627b',
      muted: '#78849a',
    },
    accents: {
      primary: '#ff7043',
      secondary: '#7c5cfc',
      success: '#18a979',
      attention: '#f5a524',
      info: '#2f80ed',
    },
    font: fonts,
    frameBackground:
      'radial-gradient(110% 75% at 50% 0%, rgba(255,190,92,0.24), transparent 64%)',
    chrome: {progressHeight: 8, progressOpacity: 0.9, captionRadius: 24},
  },
  {
    id: 'fun',
    color: {
      bg: '#120a2a',
      bgDeep: '#090416',
      surface: '#24124a',
      surfaceHi: '#321966',
      line: '#54318a',
      lineHi: '#7b4cc4',
      text: '#fff9ff',
      textDim: '#dacdf1',
      muted: '#a895c8',
    },
    accents: {
      primary: '#ff4fd8',
      secondary: '#8b5cf6',
      success: '#4fffb0',
      attention: '#ffe45e',
      info: '#45d6ff',
    },
    font: fonts,
    frameBackground:
      'radial-gradient(100% 80% at 50% 0%, rgba(255,79,216,0.20), transparent 58%)',
    chrome: {progressHeight: 10, progressOpacity: 1, captionRadius: 999},
  },
];

export const DEFAULT_TEMPLATES: TemplateDefinition[] = [
  {
    id: 'concept-explainer',
    label: 'Concept explainer',
    description: 'A clear hook, repeatable explanation beats, and a concise recap.',
    slots: [
      {
        id: 'hook',
        label: 'Opening hook',
        sceneType: 'title',
        durationSeconds: 4,
        required: true,
        repeatable: false,
        defaultProps: {kicker: 'Explained visually'},
      },
      {
        id: 'explanation',
        label: 'Explanation',
        sceneType: 'callout',
        durationSeconds: 7,
        required: true,
        repeatable: true,
        defaultProps: {},
      },
      {
        id: 'recap',
        label: 'Recap',
        sceneType: 'outro',
        durationSeconds: 5,
        required: false,
        repeatable: false,
        defaultProps: {},
      },
    ],
  },
  {
    id: 'quick-lesson',
    label: 'Quick lesson',
    description: 'Friendly learning cards with a short review at the end.',
    slots: [
      {
        id: 'welcome',
        label: 'Welcome',
        sceneType: 'title',
        durationSeconds: 4,
        required: true,
        repeatable: false,
        defaultProps: {kicker: 'Learn fast'},
      },
      {
        id: 'lesson-card',
        label: 'Lesson card',
        sceneType: 'callout',
        durationSeconds: 5,
        required: true,
        repeatable: true,
        defaultProps: {},
      },
      {
        id: 'quick-check',
        label: 'Quick check',
        sceneType: 'outro',
        durationSeconds: 5,
        required: false,
        repeatable: false,
        defaultProps: {cta: 'Can you remember them all?'},
      },
    ],
  },
  {
    id: 'fun-loop',
    label: 'Fun loop',
    description: 'A fast setup, punchy beats, and a loop-friendly finish.',
    slots: [
      {
        id: 'setup',
        label: 'Setup',
        sceneType: 'title',
        durationSeconds: 3,
        required: true,
        repeatable: false,
        defaultProps: {kicker: 'Wait for it'},
      },
      {
        id: 'beat',
        label: 'Beat',
        sceneType: 'bigStat',
        durationSeconds: 3,
        required: true,
        repeatable: true,
        defaultProps: {},
      },
      {
        id: 'loop',
        label: 'Loop',
        sceneType: 'outro',
        durationSeconds: 3,
        required: false,
        repeatable: false,
        defaultProps: {cta: 'Watch it again'},
      },
    ],
  },
  {
    id: 'tech-reel-concept',
    label: 'Tech reel — concept',
    description:
      'A 60-second mental-model explainer for YouTube Shorts and Instagram Reels.',
    slots: [
      {
        id: 'hook',
        label: 'Hook',
        sceneType: 'title',
        durationSeconds: 3,
        required: true,
        repeatable: false,
        defaultProps: {kicker: 'Python to AI Engineer'},
      },
      {
        id: 'concept-beat',
        label: 'Concept beat',
        sceneType: 'callout',
        durationSeconds: 8,
        required: true,
        repeatable: true,
        defaultProps: {attribution: 'Build the mental model'},
      },
      {
        id: 'recap',
        label: 'Recap',
        sceneType: 'outro',
        durationSeconds: 6,
        required: true,
        repeatable: false,
        defaultProps: {cta: 'Continue the Python to AI Engineer path'},
      },
    ],
  },
  {
    id: 'tech-reel-runtime',
    label: 'Tech reel — visual runtime lesson',
    description:
      'A 60-second code lesson with a mental model, runnable example, runtime trace, terminal output, architecture connection, and decision rule.',
    slots: [
      {
        id: 'hook',
        label: 'Hook',
        sceneType: 'title',
        durationSeconds: 3,
        required: true,
        repeatable: false,
        defaultProps: {kicker: 'Python to AI Engineer'},
      },
      {
        id: 'mental-model',
        label: 'Mental model',
        sceneType: 'flow',
        durationSeconds: 8,
        required: true,
        repeatable: false,
        defaultProps: {},
      },
      {
        id: 'runnable-example',
        label: 'Runnable example',
        sceneType: 'code',
        durationSeconds: 9,
        required: true,
        repeatable: false,
        defaultProps: {lang: 'python', filename: 'example.py'},
      },
      {
        id: 'runtime-trace',
        label: 'Runtime trace',
        sceneType: 'steps',
        durationSeconds: 9,
        required: true,
        repeatable: false,
        defaultProps: {},
      },
      {
        id: 'observable-output',
        label: 'Observable output',
        sceneType: 'terminal',
        durationSeconds: 8,
        required: true,
        repeatable: false,
        defaultProps: {},
      },
      {
        id: 'ai-connection',
        label: 'AI engineering connection',
        sceneType: 'architecture',
        durationSeconds: 9,
        required: true,
        repeatable: false,
        defaultProps: {},
      },
      {
        id: 'decision-rule',
        label: 'Decision rule',
        sceneType: 'compare',
        durationSeconds: 8,
        required: true,
        repeatable: false,
        defaultProps: {},
      },
      {
        id: 'recap',
        label: 'Recap',
        sceneType: 'outro',
        durationSeconds: 6,
        required: true,
        repeatable: false,
        defaultProps: {cta: 'Continue the Python to AI Engineer path'},
      },
    ],
  },
  {
    id: 'tech-reel-code',
    label: 'Tech reel — code concept',
    description:
      'A 60-second before/after code lesson for syntax and runtime concepts.',
    slots: [
      {
        id: 'hook',
        label: 'Hook',
        sceneType: 'title',
        durationSeconds: 3,
        required: true,
        repeatable: false,
        defaultProps: {kicker: 'Python to AI Engineer'},
      },
      {
        id: 'code-beat',
        label: 'Code beat',
        sceneType: 'code',
        durationSeconds: 10,
        required: true,
        repeatable: true,
        defaultProps: {
          lang: 'python',
          filename: 'example.py',
          lines: ['# Add the runnable example here'],
        },
      },
      {
        id: 'recap',
        label: 'Recap',
        sceneType: 'outro',
        durationSeconds: 6,
        required: true,
        repeatable: false,
        defaultProps: {cta: 'Try the example locally'},
      },
    ],
  },
  {
    id: 'tech-reel-compare',
    label: 'Tech reel — comparison',
    description:
      'A 60-second decision guide for two commonly confused engineering choices.',
    slots: [
      {
        id: 'hook',
        label: 'Hook',
        sceneType: 'title',
        durationSeconds: 3,
        required: true,
        repeatable: false,
        defaultProps: {kicker: 'Know the difference'},
      },
      {
        id: 'comparison',
        label: 'Comparison',
        sceneType: 'compare',
        durationSeconds: 10,
        required: true,
        repeatable: true,
        defaultProps: {
          left: {heading: 'Option A', points: ['First responsibility']},
          right: {heading: 'Option B', points: ['Second responsibility']},
        },
      },
      {
        id: 'recap',
        label: 'Decision rule',
        sceneType: 'outro',
        durationSeconds: 6,
        required: true,
        repeatable: false,
        defaultProps: {cta: 'Choose by constraint, not popularity'},
      },
    ],
  },
  {
    id: 'tech-youtube-deep-dive',
    label: 'Tech YouTube — 5–30-minute deep dive',
    description:
      'A long-form lesson with repeatable 30-second chapters, examples, tradeoffs, and a production recap.',
    slots: [
      {
        id: 'hook',
        label: 'Hook',
        sceneType: 'title',
        durationSeconds: 3,
        required: true,
        repeatable: false,
        defaultProps: {kicker: 'Python to AI Engineer'},
      },
      {
        id: 'chapter',
        label: 'Chapter',
        sceneType: 'steps',
        durationSeconds: 30,
        required: true,
        repeatable: true,
        defaultProps: {
          kicker: 'Chapter',
          items: [
            {label: 'Mental model'},
            {label: 'Mechanics'},
            {label: 'Production use'},
          ],
        },
      },
      {
        id: 'recap',
        label: 'Recap',
        sceneType: 'outro',
        durationSeconds: 6,
        required: true,
        repeatable: false,
        defaultProps: {cta: 'Continue the Python to AI Engineer path'},
      },
    ],
  },
];

const commonVoice = {
  model: 'mlx-community/Kokoro-82M-bf16',
  language: 'a',
  targetLufs: -14,
  truePeakDb: -1.5,
  loudnessRange: 11,
};

export const DEFAULT_CATEGORIES: CategoryDefinition[] = [
  {
    id: 'tech',
    label: 'AI Data Dynamics',
    shortLabel: 'Tech, visually',
    handle: '@AIDataDynamics',
    defaultDeliveries: ['youtube-long', 'instagram-reel'],
    defaultTemplateId: 'concept-explainer',
    defaultThemeId: 'tech',
    defaultCta: 'Follow for more',
    defaultHashtags: {
      youtube: ['technology', 'programming', 'ai'],
      instagram: ['tech', 'programming', 'artificialintelligence'],
    },
    voice: {...commonVoice, preset: 'am_adam', speed: 1, maxSpeed: 1},
    editorial: {minSeconds: 20, maxSeconds: 1_800, maxNarrationWpm: 165},
  },
  {
    id: 'learn',
    label: 'Learn Fast',
    shortLabel: 'Learn it fast',
    handle: '@LearnChannel',
    defaultDeliveries: ['youtube-short', 'instagram-reel'],
    defaultTemplateId: 'quick-lesson',
    defaultThemeId: 'learn',
    defaultCta: 'Try the quick check',
    defaultHashtags: {
      youtube: ['learning', 'students', 'education'],
      instagram: ['learnfast', 'studentlife', 'education'],
    },
    voice: {...commonVoice, preset: 'af_heart', speed: 1, maxSpeed: 1},
    editorial: {
      minSeconds: 20,
      maxSeconds: 1_800,
      maxNarrationWpm: 170,
      requiresAgeBand: true,
      requiresLearningObjective: true,
      requiresSafetyReview: true,
    },
  },
  {
    id: 'fun',
    label: 'Fun Loop',
    shortLabel: 'Wait for it',
    handle: '@FunChannel',
    defaultDeliveries: ['youtube-short', 'instagram-reel'],
    defaultTemplateId: 'fun-loop',
    defaultThemeId: 'fun',
    defaultCta: 'Watch it loop',
    defaultHashtags: {
      youtube: ['fun', 'shorts', 'challenge'],
      instagram: ['funreels', 'challenge', 'watchtillend'],
    },
    voice: {...commonVoice, preset: 'af_sky', speed: 1, maxSpeed: 1},
    editorial: {minSeconds: 8, maxSeconds: 1_800, maxNarrationWpm: 230},
  },
];
