import type {VideoSpec} from '@video-kit/core/spec';

export const agenticRag: VideoSpec = {
  channel: 'tech',
  slug: 'agentic-rag',
  title: 'How Agentic RAG works',
  template: 'concept-explainer',
  summary: 'How an AI agent decides when to retrieve, checks evidence, retries weak searches, and answers with grounded context.',
  deliveries: ['youtube-long', 'instagram-reel'],
  audience: {level: 'intermediate'},
  editorial: {
    language: 'en',
    objective: 'Explain the decision loop that makes Agentic RAG different from a fixed retrieve-then-generate pipeline.',
    sources: [
      {
        title: 'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks',
        url: 'https://arxiv.org/abs/2005.11401',
      },
      {
        title: 'Build a custom RAG agent with LangGraph',
        url: 'https://docs.langchain.com/oss/python/langgraph/agentic-rag',
      },
    ],
  },
  scenes: [
    {
      type: 'title',
      durationInFrames: 90,
      kicker: 'AI, visually',
      title: 'Agentic RAG',
      subtitle: 'RAG with a decision loop, not a fixed pipeline.',
      narration: 'Agentic RAG lets the model control how it finds evidence.',
    },
    {
      type: 'compare',
      durationInFrames: 240,
      kicker: 'The difference',
      title: 'Pipeline versus decision loop',
      left: {
        heading: 'Classic RAG',
        points: ['retrieve every time', 'one search query', 'generate once'],
        accent: 'info',
      },
      right: {
        heading: 'Agentic RAG',
        points: ['chooses when to search', 'rewrites weak queries', 'checks evidence first'],
        accent: 'success',
      },
      narration: 'Classic RAG follows one fixed path. Agentic RAG decides whether to search, reformulate, retry, or answer.',
    },
    {
      type: 'architecture',
      durationInFrames: 450,
      kicker: 'One question',
      title: 'Follow the control loop',
      accent: 'success',
      nodes: [
        {id: 'question', label: 'Question', sub: 'user intent', col: 0, row: 0, accent: 'info'},
        {id: 'agent', label: 'Agent', sub: 'choose action', col: 1, row: 0, accent: 'primary'},
        {id: 'retriever', label: 'Retriever', sub: 'search tools', col: 2, row: 0, accent: 'secondary'},
        {id: 'evidence', label: 'Evidence', sub: 'ranked chunks', col: 2, row: 1, accent: 'info'},
        {id: 'grader', label: 'Grader', sub: 'relevant?', col: 1, row: 1, accent: 'attention'},
        {id: 'answer', label: 'Answer', sub: 'grounded output', col: 0, row: 1, accent: 'success'},
      ],
      edges: [
        {from: 'question', to: 'agent'},
        {from: 'agent', to: 'retriever', label: 'search'},
        {from: 'retriever', to: 'evidence', label: 'fetch'},
        {from: 'evidence', to: 'grader', label: 'check'},
        {from: 'grader', to: 'agent', label: 'rewrite + retry', dashed: true},
        {from: 'grader', to: 'answer', label: 'ground'},
      ],
      reveal: [['question'], ['agent'], ['retriever'], ['evidence'], ['grader'], ['answer']],
      trace: {
        path: ['question', 'agent', 'retriever', 'evidence', 'grader', 'answer'],
        label: 'following a successful retrieval',
      },
      narration: 'The agent reads the question and chooses a tool. The retriever returns evidence. A grader checks relevance. Weak evidence loops back; strong evidence grounds the answer.',
    },
    {
      type: 'steps',
      durationInFrames: 270,
      kicker: 'The agent decides',
      items: [
        {label: 'Do I need retrieval?', detail: 'Answer directly or call a search tool', accent: 'info'},
        {label: 'What should I search?', detail: 'Rewrite or split the question', accent: 'primary'},
        {label: 'Is the evidence useful?', detail: 'Grade relevance before generation', accent: 'attention'},
        {label: 'Retry or answer?', detail: 'Loop with limits, or produce the response', accent: 'success'},
      ],
      footnote: 'The branching is the “agentic” part.',
      narration: 'At every branch, the model selects the next action: search, rewrite, evaluate, retry, or finish.',
    },
    {
      type: 'code',
      durationInFrames: 330,
      kicker: 'The mental model',
      title: 'A loop with two exits',
      lang: 'python',
      filename: 'agentic_rag.py',
      accent: 'success',
      lines: [
        'while steps < LIMIT:',
        '    action = agent.decide(state)',
        '    if action.is_search:',
        '        evidence = search(action.query)',
        '        evidence = grade(evidence)',
        '    else:',
        '        return answer(evidence)',
      ],
      focus: [
        {lines: [1, 2, 3], note: 'The model chooses whether retrieval is the next useful action.'},
        {lines: [4, 5], note: 'Search results are checked before they become answer context.'},
        {lines: [1, 7], note: 'A step limit prevents endless retries; sufficient evidence exits the loop.'},
      ],
      narration: 'In code, the agent chooses an action, searches when needed, grades the results, and stops when it can answer.',
    },
    {
      type: 'callout',
      durationInFrames: 210,
      text: 'The agent owns the retrieval loop.',
      attribution: 'more adaptive, but not free',
      accent: 'primary',
      narration: 'That flexibility costs extra model calls and latency, so production systems need budgets, stopping rules, traces, and evaluations.',
    },
    {
      type: 'outro',
      durationInFrames: 210,
      recap: ['decide → retrieve', 'grade → retry', 'evidence → answer'],
      tagline: 'AI systems, drawn out.',
      narration: 'That is Agentic RAG: decide, retrieve, grade, retry when needed, then answer from evidence.',
    },
  ],
};
