import type {VideoSpec} from '@video-kit/core/spec';

export const contextVsHarnessEngineering: VideoSpec = {
  channel: 'tech',
  slug: 'context-vs-harness-engineering',
  title: 'Context Engineering vs Harness Engineering',
  template: 'concept-explainer',
  summary:
    'Context engineering controls what an AI agent sees. Harness engineering controls how the complete agent system executes, verifies, and recovers.',
  fps: 30,
  deliveries: ['youtube-short', 'instagram-reel'],
  audience: {level: 'beginner'},
  captions: true,

  // Generated by the local TTS pipeline. Paths are relative to public/.
  audio: 'audio/tech/context-vs-harness-engineering/master.wav',
  captionTimings:
    'audio/tech/context-vs-harness-engineering/words.json',

  editorial: {
    language: 'en',
    objective:
      'Explain the different responsibilities of context engineering and harness engineering.',
    sources: [
      {
        title:
          'OpenAI — Harness engineering: leveraging Codex in an agent-first world',
        url: 'https://openai.com/index/harness-engineering/',
      },
      {
        title: 'Anthropic — Effective harnesses for long-running agents',
        url: 'https://www.anthropic.com/engineering/effective-harnesses-for-long-running-agents',
      },
    ],
  },

  scenes: [
    {
      id: 'hook',
      type: 'title',
      durationInFrames: 90,
      kicker: 'AI engineering, visually',
      title: 'Context vs Harness',
      subtitle: 'What the agent sees versus how the system controls it.',
      narration:
        'Context engineering and harness engineering solve different agent problems.',
    },

    {
      id: 'difference',
      type: 'compare',
      durationInFrames: 240,
      kicker: 'The difference',
      title: 'Information versus environment',
      left: {
        heading: 'Context Engineering',
        points: [
          'what the model sees',
          'instructions and examples',
          'documents, memory, tool results',
        ],
        accent: 'info',
      },
      right: {
        heading: 'Harness Engineering',
        points: [
          'what the agent can do',
          'tools, permissions, and limits',
          'tests, feedback, and recovery',
        ],
        accent: 'success',
      },
      narration:
        'Context engineering decides what the agent sees: instructions, examples, retrieved documents, memory, and the results returned by its tools.',
    },

    {
      id: 'context-layer',
      type: 'architecture',
      durationInFrames: 360,
      kicker: 'Inside the run',
      title: 'Build the right context',
      accent: 'info',
      nodes: [
        {
          id: 'task',
          label: 'Task',
          sub: 'user intent',
          col: 0,
          row: 0,
          accent: 'attention',
        },
        {
          id: 'builder',
          label: 'Context Builder',
          sub: 'select relevant information',
          col: 1,
          row: 0,
          accent: 'info',
        },
        {
          id: 'model',
          label: 'Model',
          sub: 'reason and choose',
          col: 2,
          row: 0,
          accent: 'primary',
        },
        {
          id: 'result',
          label: 'Tool Result',
          sub: 'new context',
          col: 1,
          row: 1,
          accent: 'success',
        },
      ],
      edges: [
        {from: 'task', to: 'builder', label: 'intent'},
        {from: 'builder', to: 'model', label: 'context'},
        {from: 'model', to: 'result', label: 'tool call'},
        {from: 'result', to: 'builder', label: 'update', dashed: true},
      ],
      reveal: [['task'], ['builder'], ['model'], ['result']],
      trace: {
        path: ['task', 'builder', 'model', 'result', 'builder'],
        label: 'context changes during the run',
      },
      narration:
        'The task enters a context builder, which selects relevant information and gives it to the model. Better context helps the model choose a useful next action.',
    },

    {
      id: 'harness-layer',
      type: 'steps',
      durationInFrames: 300,
      kicker: 'Around the run',
      items: [
        {
          label: 'Tools',
          detail: 'Give the agent controlled ways to act',
          accent: 'info',
        },
        {
          label: 'Constraints',
          detail: 'Permissions, budgets, and architecture rules',
          accent: 'attention',
        },
        {
          label: 'Feedback',
          detail: 'Tests, linters, logs, and evaluations',
          accent: 'primary',
        },
        {
          label: 'Recovery',
          detail: 'Retry, repair, stop, or request review',
          accent: 'success',
        },
      ],
      footnote: 'The harness turns a model call into an operating system.',
      narration:
        'Harness engineering designs the environment around that model: tools, permissions, repository structure, tests, limits, logs, and reliable ways to recover from failure.',
    },

    {
      id: 'relationship',
      type: 'compare',
      durationInFrames: 300,
      kicker: 'How they work together',
      title: 'One run versus the whole system',
      left: {
        heading: 'Context',
        points: [
          'improves reasoning',
          'changes during the task',
          'lives inside the model call',
        ],
        accent: 'info',
      },
      right: {
        heading: 'Harness',
        points: [
          'controls execution',
          'checks the result',
          'feeds failure back into the loop',
        ],
        accent: 'success',
      },
      narration:
        'Context improves the agent’s reasoning inside one run. The harness controls the entire run, then feeds failures back as retries, tests, or better rules.',
    },

    {
      id: 'mental-model',
      type: 'callout',
      durationInFrames: 240,
      text: 'Context shapes the decision. The harness shapes the system.',
      attribution: 'They are complementary, not competing.',
      accent: 'primary',
      narration:
        'They are not competing ideas. Context provides the map; the harness provides the roads, guardrails, instruments, and feedback loop.',
    },

    {
      id: 'outro',
      type: 'outro',
      durationInFrames: 270,
      recap: [
        'context → what the model sees',
        'harness → how the agent operates',
        'both → reliable autonomous work',
      ],
      tagline: 'AI systems, drawn out.',
      narration:
        'Use context engineering to help the model understand. Use harness engineering to help the whole agent system execute, verify, recover, and improve.',
    },
  ],
};
