import type {VideoSpec} from '@video-kit/core/spec';

/**
 * Five-minute beginner explainer of retrieval-augmented generation.
 *
 * The scene timeline is exactly 9,000 frames at 30 fps. Narration lives beside
 * the visuals so captions, chapters, TTS, and the final render cannot drift.
 */
export const ragFundamentals: VideoSpec = {
  channel: 'tech',
  slug: 'rag-fundamentals',
  title: 'What Is RAG? Why It Matters and How It Works',
  template: 'long-form-concept-explainer',
  summary:
    'A visual, runtime-first explanation of retrieval-augmented generation, from document indexing through retrieval, grounded generation, evaluation, and production controls.',
  fps: 30,
  deliveries: ['youtube-long'],
  audience: {level: 'beginner'},
  captions: true,
  voice: {speed: 1, maxSpeed: 1},
  audio: 'audio/tech/rag-fundamentals/master.wav',
  captionTimings: 'audio/tech/rag-fundamentals/words.json',
  soundtrack: {
    music: {
      src: 'audio/music/quiet-circuit-ambient.m4a',
      credit: 'Video Kit — Quiet Circuit Ambient',
      license: 'Original project-generated instrumental',
      volume: 0.22,
      loop: false,
      fadeInFrames: 150,
      fadeOutFrames: 150,
    },
    ducking: {gain: 0.52, attackFrames: 12, releaseFrames: 24},
  },
  editorial: {
    language: 'en-US',
    objective:
      'Explain why RAG exists, distinguish indexing from retrieval-time generation, trace the runtime path, and show the controls needed for reliable production use.',
    safetyStatus: 'approved',
    sources: [
      {
        title: 'Lewis et al. — Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks',
        url: 'https://arxiv.org/abs/2005.11401',
      },
      {
        title: 'Microsoft Foundry — Retrieval augmented generation and indexes',
        url: 'https://learn.microsoft.com/en-us/azure/foundry/concepts/retrieval-augmented-generation',
      },
      {
        title: 'Azure Architecture Center — Design and develop a RAG solution',
        url: 'https://learn.microsoft.com/en-us/azure/architecture/ai-ml/guide/rag/rag-solution-design-and-evaluation-guide',
      },
      {
        title: 'OpenAI API — Vector store files and chunking strategy',
        url: 'https://platform.openai.com/docs/api-reference/vector-stores-files',
      },
    ],
  },
  scenes: [
    {
      id: 'hook',
      type: 'title',
      durationInFrames: 75,
      kicker: 'RAG fundamentals',
      title: 'What if the model never saw your data?',
      subtitle: 'Retrieve first. Generate with evidence.',
      narration:
        'Your private knowledge is missing.',
    },
    {
      id: 'knowledge-gap',
      type: 'compare',
      durationInFrames: 735,
      chapterTitle: 'Why RAG exists',
      kicker: 'The knowledge gap',
      title: 'Model memory is not your live knowledge base',
      left: {
        heading: 'LLM alone',
        points: [
          'Knowledge bounded by training and current context',
          'No automatic access to private files',
          'Can answer when evidence is missing',
        ],
        accent: 'attention',
      },
      right: {
        heading: 'RAG application',
        points: [
          'Searches approved sources at runtime',
          'Adds relevant evidence to context',
          'Can expose citations and uncertainty',
        ],
        accent: 'success',
      },
      narration:
        'A language model answers from patterns learned during training and from the context it receives now. That creates a gap. Your company policies may be private, product documentation may change weekly, and the model may confidently complete an answer when evidence is missing. Constantly retraining for every document update is slow, expensive, and usually the wrong tool. RAG addresses this knowledge gap at runtime.',
    },
    {
      id: 'definition',
      type: 'flow',
      durationInFrames: 660,
      chapterTitle: 'What RAG means',
      kicker: 'Retrieval-augmented generation',
      title: 'Search first, then answer with evidence',
      steps: [
        {label: 'Question', detail: 'What does the user need?', accent: 'info'},
        {label: 'Retrieve', detail: 'Find relevant passages', accent: 'primary'},
        {label: 'Augment', detail: 'Add evidence to context', accent: 'attention'},
        {label: 'Generate', detail: 'Answer and cite sources', accent: 'success'},
      ],
      narration:
        'RAG means retrieval-augmented generation. Retrieval finds information relevant to the user’s question. Augmentation places that evidence into the model’s input. Generation uses the question, instructions, and retrieved context to create the answer. Search first, then ask the model to answer with evidence. RAG is an application pattern, not a model setting.',
    },
    {
      id: 'two-pipelines',
      type: 'architecture',
      durationInFrames: 900,
      chapterTitle: 'The complete architecture',
      kicker: 'Two connected pipelines',
      title: 'Prepare knowledge offline. Answer online.',
      nodes: [
        {id: 'sources', label: 'Sources', sub: 'trusted documents', col: 0, row: 0, accent: 'info'},
        {id: 'indexing', label: 'Indexing', sub: 'chunk + enrich + encode', col: 1, row: 0, accent: 'primary'},
        {id: 'index', label: 'Search Index', sub: 'text + vectors + metadata', col: 2, row: 0, accent: 'attention'},
        {id: 'question', label: 'Question', sub: 'online request', col: 0, row: 1, accent: 'info'},
        {id: 'retrieval', label: 'Retrieval', sub: 'filter + search + rerank', col: 1, row: 1, accent: 'primary'},
        {id: 'answer', label: 'Grounded Answer', sub: 'response + citations', col: 2, row: 1, accent: 'success'},
      ],
      edges: [
        {from: 'sources', to: 'indexing'},
        {from: 'indexing', to: 'index'},
        {from: 'question', to: 'retrieval'},
        {from: 'index', to: 'retrieval', dashed: true},
        {from: 'retrieval', to: 'answer'},
      ],
      reveal: [
        ['sources', 'indexing', 'index'],
        ['question', 'retrieval', 'answer'],
      ],
      trace: {path: ['question', 'retrieval', 'answer'], label: 'the live request'},
      narration:
        'A RAG system has two pipelines. The indexing pipeline runs before users ask questions. It prepares documents and stores searchable representations. The answering pipeline starts when a question arrives. It searches the index, selects passages, builds the model context, and requests an answer. These pipelines can change independently. You can refresh documents without retraining the language model, and improve retrieval without replacing the generator. That separation is one reason RAG is practical.',
    },
    {
      id: 'indexing',
      type: 'motionCanvas',
      durationInFrames: 1_020,
      chapterTitle: 'Indexing documents',
      style: 'midnight-code',
      motion: {intensity: 'dynamic', ambient: true},
      effects: {
        camera: 'push-in',
        particles: 'data-stream',
        glow: 'soft',
        scanlines: true,
        vignette: true,
      },
      headline: 'Build searchable knowledge',
      narration:
        'During indexing, the application loads documents, cleans them, and splits them into chunks. Good chunk boundaries preserve enough meaning to answer a question without sending an entire manual. Each chunk should retain metadata such as source, title, date, permissions, and version. In a common vector-search design, an embedding model converts each chunk into a numeric vector and stores the vector beside the original text. Keyword or hybrid indexes can also participate. The goal is not vectors for their own sake. The goal is a searchable collection that can return the right evidence.',
      elements: [
        {id: 'heading', kind: 'text', text: 'INDEXING PIPELINE', role: 'headline', x: 50, y: 8, width: 90},
        {id: 'source-doc', kind: 'shape', shape: 'document', label: 'Policy manual', sublabel: 'trusted source', x: 12, y: 42, width: 17, height: 23, tone: 'neutral', animation: 'float'},
        {id: 'splitter', kind: 'shape', shape: 'diamond', label: 'split', sublabel: 'semantic boundaries', x: 34, y: 42, width: 14, height: 18, tone: 'accent', animation: 'wobble'},
        {id: 'chunks', kind: 'cluster', label: 'chunks + metadata', x: 51, y: 42, width: 24, height: 27},
        {id: 'embedder', kind: 'shape', shape: 'hexagon', label: 'embed', sublabel: 'text → vector', x: 70, y: 42, width: 15, height: 19, tone: 'positive', animation: 'breathe'},
        {id: 'vector-index', kind: 'shape', shape: 'database', label: 'search index', sublabel: 'text + vectors + metadata', x: 89, y: 42, width: 17, height: 24, tone: 'neutral', animation: 'float'},
        {id: 'source-to-split', kind: 'connector', from: 'source-doc', to: 'splitter', label: 'clean', arrow: true},
        {id: 'split-to-chunks', kind: 'connector', from: 'splitter', to: 'chunks', label: 'chunk', arrow: true},
        {id: 'chunks-to-embed', kind: 'connector', from: 'chunks', to: 'embedder', label: 'enrich', arrow: true},
        {id: 'embed-to-index', kind: 'connector', from: 'embedder', to: 'vector-index', label: 'store', arrow: true},
        {id: 'metadata', kind: 'text', text: 'SOURCE · TITLE · DATE · VERSION · PERMISSIONS', role: 'payoff', x: 50, y: 75, width: 88},
        {id: 'goal', kind: 'text', text: 'Goal: return the right evidence', role: 'cta', x: 50, y: 88, width: 88},
      ],
      actions: [
        {target: 'heading', type: 'reveal', atFrame: 0, durationFrames: 18},
        {target: 'source-doc', type: 'reveal', atFrame: 55, durationFrames: 20},
        {target: 'source-to-split', type: 'draw', atFrame: 125, durationFrames: 28},
        {target: 'splitter', type: 'reveal', atFrame: 165, durationFrames: 20},
        {target: 'splitter', type: 'spin', atFrame: 220, durationFrames: 45},
        {target: 'split-to-chunks', type: 'travel', atFrame: 275, durationFrames: 50},
        {target: 'chunks', type: 'reveal', atFrame: 330, durationFrames: 22},
        {target: 'metadata', type: 'reveal', atFrame: 420, durationFrames: 22},
        {target: 'metadata', type: 'highlight', atFrame: 480, durationFrames: 50},
        {target: 'chunks-to-embed', type: 'draw', atFrame: 560, durationFrames: 30},
        {target: 'embedder', type: 'reveal', atFrame: 610, durationFrames: 22},
        {target: 'embedder', type: 'pulse', atFrame: 665, durationFrames: 48},
        {target: 'embed-to-index', type: 'travel', atFrame: 735, durationFrames: 54},
        {target: 'vector-index', type: 'reveal', atFrame: 790, durationFrames: 22},
        {target: 'vector-index', type: 'pulse', atFrame: 835, durationFrames: 48},
        {target: 'goal', type: 'reveal', atFrame: 930, durationFrames: 24},
      ],
    },
    {
      id: 'retrieval',
      type: 'architecture',
      durationInFrames: 1_005,
      chapterTitle: 'Retrieving evidence',
      kicker: 'Question-time pipeline',
      title: 'Filter, search, rerank, select',
      nodes: [
        {id: 'identity', label: 'Identity', sub: 'user + permissions', col: 0, row: 0, accent: 'attention'},
        {id: 'query', label: 'Question', sub: 'refund policy?', col: 0, row: 1, accent: 'info'},
        {id: 'search', label: 'Hybrid Search', sub: 'vector + keyword', col: 1, row: 0, span: 1, accent: 'primary'},
        {id: 'candidates', label: 'Candidates', sub: 'broad first pass', col: 2, row: 0, accent: 'secondary'},
        {id: 'rerank', label: 'Reranker', sub: 'whole-query relevance', col: 1, row: 1, accent: 'attention'},
        {id: 'passages', label: 'Top Passages', sub: 'fit context budget', col: 2, row: 1, accent: 'success'},
      ],
      edges: [
        {from: 'identity', to: 'search', label: 'access filter'},
        {from: 'query', to: 'search'},
        {from: 'search', to: 'candidates'},
        {from: 'candidates', to: 'rerank'},
        {from: 'rerank', to: 'passages'},
      ],
      reveal: [
        ['identity', 'query'],
        ['search', 'candidates'],
        ['rerank', 'passages'],
      ],
      trace: {
        path: ['query', 'search', 'candidates', 'rerank', 'passages'],
        label: 'evidence selection',
        accent: 'success',
      },
      narration:
        'At question time, the application applies access rules so users retrieve only permitted documents. It converts the question into the representation expected by the search system, then runs vector, keyword, or hybrid retrieval. The first search may return many candidates. Metadata filters remove incompatible results, and a reranker can reorder passages by their relevance to the complete question. Finally, the application chooses a small set that fits the model’s context budget. Retrieval quality determines which facts the model is even able to use.',
    },
    {
      id: 'augmentation',
      type: 'code',
      durationInFrames: 810,
      chapterTitle: 'Augmenting the prompt',
      kicker: 'Evidence becomes context',
      title: 'Keep instructions, question, and evidence distinct',
      filename: 'rag_prompt.py',
      lang: 'python',
      lines: [
        'question = "What is our refund policy?"',
        'passages = retrieve(question, user_id="u_42")',
        '',
        'prompt = f"""',
        'Answer only from CONTEXT.',
        'Cite source ids. Say when evidence is insufficient.',
        '',
        'CONTEXT:',
        '{format_with_source_ids(passages)}',
        '',
        'QUESTION: {question}',
        '"""',
        '',
        'answer = llm.generate(prompt)',
      ],
      focus: [
        {lines: [1, 2], note: 'retrieve only what this user may access'},
        {lines: [5, 6], note: 'define evidence and refusal behavior'},
        {lines: [8, 9], note: 'keep source ids attached'},
        {lines: [11, 14], note: 'send the assembled runtime context'},
      ],
      narration:
        'The application builds a prompt from instructions, the question, and passages. An instruction might say: answer only from context, cite the source identifiers, and state when the evidence is insufficient. The retrieved text remains untrusted data, because documents can contain misleading or malicious instructions. Systems separate instructions from evidence, limit what tools the model can call, and keep source identifiers attached so the answer can point back to sources.',
    },
    {
      id: 'grounded-generation',
      type: 'architecture',
      durationInFrames: 810,
      chapterTitle: 'Generating a grounded answer',
      kicker: 'Normal inference, better context',
      title: 'Generate, cite, or say “not enough evidence”',
      nodes: [
        {id: 'instructions', label: 'Instructions', sub: 'answer rules', col: 0, row: 0, accent: 'primary'},
        {id: 'evidence', label: 'Evidence', sub: 'selected passages', col: 0, row: 1, accent: 'info'},
        {id: 'llm', label: 'LLM Inference', sub: 'weights unchanged', col: 1, row: 0, span: 1, accent: 'attention'},
        {id: 'answer', label: 'Answer', sub: 'grounded claims', col: 2, row: 0, accent: 'success'},
        {id: 'citations', label: 'Citations', sub: 'source traceability', col: 2, row: 1, accent: 'info'},
        {id: 'refusal', label: 'Insufficient Evidence', sub: 'safe fallback', col: 1, row: 1, accent: 'secondary'},
      ],
      edges: [
        {from: 'instructions', to: 'llm'},
        {from: 'evidence', to: 'llm'},
        {from: 'llm', to: 'answer'},
        {from: 'answer', to: 'citations'},
        {from: 'llm', to: 'refusal', dashed: true},
      ],
      reveal: [
        ['instructions', 'evidence'],
        ['llm'],
        ['answer', 'citations', 'refusal'],
      ],
      trace: {path: ['evidence', 'llm', 'answer', 'citations'], label: 'traceable claim'},
      narration:
        'The language model performs inference. It does not update its weights. It reads the context and predicts an answer token by token. The application can return the answer with citations, expose the passages used, or refuse when retrieval found no adequate support. This is why grounded matters: claims should be traceable to evidence. Grounding can reduce unsupported output, but it does not prove that every generated sentence is correct. Verification still matters.',
    },
    {
      id: 'why-important',
      type: 'compare',
      durationInFrames: 840,
      chapterTitle: 'Why RAG is important',
      kicker: 'Choose the right knowledge strategy',
      title: 'Knowledge access versus behavior adaptation',
      left: {
        heading: 'RAG is strong for',
        points: [
          'Private and frequently changing facts',
          'Source citations and inspection',
          'Permission-aware knowledge access',
          'Refreshing data without model training',
        ],
        accent: 'success',
      },
      right: {
        heading: 'Fine-tuning is strong for',
        points: [
          'Behavior and response style',
          'Repeated task patterns',
          'Domain-specific output structure',
          'Measured task-performance adaptation',
        ],
        accent: 'primary',
      },
      narration:
        'RAG matters because it connects models to private knowledge without placing facts in model weights. The index can be refreshed as information changes. Citations make answers inspectable and auditable. Retrieval, permissions, and source selection give the application more control over what knowledge enters the prompt. Fine-tuning is still useful for changing behavior, style, or task performance. RAG is the better starting point when the main problem is accessing current or proprietary facts.',
    },
    {
      id: 'failure-modes',
      type: 'steps',
      durationInFrames: 915,
      chapterTitle: 'Where RAG fails',
      kicker: 'RAG is not a truth machine',
      items: [
        {label: 'Source quality', detail: 'Wrong or stale documents poison the evidence', accent: 'attention'},
        {label: 'Chunking', detail: 'Facts lose their surrounding meaning', accent: 'secondary'},
        {label: 'Retrieval', detail: 'The correct passage is missed or outranked', accent: 'primary'},
        {label: 'Permissions', detail: 'Sensitive information reaches the wrong user', accent: 'attention'},
        {label: 'Generation', detail: 'The model can still misread or combine claims', accent: 'secondary'},
      ],
      footnote: 'Evaluate retrieval quality and answer faithfulness separately.',
      narration:
        'RAG is not a truth machine. Bad documents produce bad evidence. Poor chunking separates facts from explanations. Weak retrieval can miss the correct passage or return something similar. Stale indexes and incorrect permissions create security failures. Even with relevant context, the model can misunderstand, combine claims incorrectly, or ignore instructions. Evaluate retrieval and generation separately: did the system fetch evidence, and did the answer faithfully use it? User usefulness depends on both stages.',
    },
    {
      id: 'production-checklist',
      type: 'steps',
      durationInFrames: 960,
      chapterTitle: 'Production checklist',
      kicker: 'Build an evaluation loop',
      items: [
        {label: 'Sources', detail: 'authority, versions, permissions', accent: 'info'},
        {label: 'Search', detail: 'chunking, hybrid retrieval, reranking', accent: 'primary'},
        {label: 'Context', detail: 'budget, provenance, injection boundaries', accent: 'attention'},
        {label: 'Response', detail: 'citations, refusals, policy checks', accent: 'secondary'},
        {label: 'Evaluation', detail: 'evidence recall, faithfulness, usefulness', accent: 'success'},
      ],
      footnote: 'Every document, model, and prompt change can affect the full pipeline.',
      narration:
        'A production checklist starts with authoritative sources and versioning. Test chunk sizes and preserve metadata. Compare vector, keyword, and hybrid search. Apply access filters before retrieval, then rerank when measurements justify it. Build an evaluation set with questions, expected evidence, and acceptable answers. Log scores, passages, latency, citations, refusals, and feedback without leaking sensitive content. Monitor changes, because new documents, embedding models, or prompts can alter the pipeline.',
    },
    {
      id: 'outro',
      type: 'outro',
      durationInFrames: 270,
      tagline: 'Retrieve evidence before generating the answer.',
      cta: 'Subscribe for the complete AI engineering path',
      recap: [
        'PREPARE KNOWLEDGE',
        'RETRIEVE → AUGMENT → GENERATE',
        'CITE → EVALUATE → IMPROVE',
      ],
      narration:
        'Prepare knowledge, retrieve evidence, augment context, generate with citations, and evaluate. That is RAG—and why it matters.',
    },
  ],
};
