/**
 * Bakes public/fonts/*.woff2 into src/design/fontFaces.ts as base64 data URIs.
 *
 * Inlining matters: it removes the network from the render loop entirely, which
 * is what makes renders deterministic on CI and inside sandboxes. Re-run with
 * `npm run fonts` after adding or swapping a face.
 */
import {readFileSync, writeFileSync} from 'node:fs';
import {join} from 'node:path';

const FACES = [
  ['Fraunces', 600, 'fraunces-latin-600-normal.woff2'],
  ['Fraunces', 700, 'fraunces-latin-700-normal.woff2'],
  ['Hanken Grotesk', 400, 'hanken-grotesk-latin-400-normal.woff2'],
  ['Hanken Grotesk', 600, 'hanken-grotesk-latin-600-normal.woff2'],
  ['Hanken Grotesk', 700, 'hanken-grotesk-latin-700-normal.woff2'],
  ['JetBrains Mono', 400, 'jetbrains-mono-latin-400-normal.woff2'],
  ['JetBrains Mono', 700, 'jetbrains-mono-latin-700-normal.woff2'],
  // Fallbacks for glyphs the latin brand subsets lack: ✓ ✕ (Symbols 2),
  // → (Symbols), ₹ (Devanagari latin-ext). Without these, those characters
  // depend on whatever system fonts the render machine happens to have.
  ['Noto Sans Symbols 2', 400, 'noto-sans-symbols-2-symbols-400-normal.woff2'],
  ['Noto Sans Symbols', 400, 'noto-sans-symbols-symbols-400-normal.woff2'],
  ['Noto Sans Devanagari', 400, 'noto-sans-devanagari-latin-ext-400-normal.woff2'],
];

const blocks = [];
const specs = [];

for (const [family, weight, file] of FACES) {
  const b64 = readFileSync(join('public/fonts', file)).toString('base64');
  blocks.push(
    `@font-face{font-family:'${family}';font-style:normal;font-weight:${weight};` +
      `font-display:block;src:url(data:font/woff2;base64,${b64}) format('woff2');}`,
  );
  specs.push(`${weight} 100px '${family}'`);
}

writeFileSync(
  'src/design/fontFaces.ts',
  `// GENERATED by scripts/gen-fonts.mjs — do not edit by hand.\n` +
    `export const FONT_SPECS: string[] = ${JSON.stringify(specs)};\n\n` +
    `export const FONT_FACE_CSS = \`${blocks.join('\n')}\`;\n`,
);

console.log(`fontFaces.ts written — ${FACES.length} faces`);
